### ISSUE TITLE
CommandTHighlightColor usage

### ISSUE THREAD

**Issue by cenouro** [wincent/command-t#128]
Hi. I have been searching around how to change highlight colors. From your documentation, I can see you provide a function for this, but I can't use it (I don't know how the parameter is codified). I have tried using 'red' instead of 'PmenuSel', but that didn't work. Can you give me some examples? Thanks.

**Comment by alistaircolling** [comment]
This is great stuff! Unfortunately though the new highlight only works for the first search.
Can anyone help?
Thanks!

**Comment by wincent** [comment]
@alistaircolling: Check out #170 and where someone has reported a similar issue.
