### ISSUE TITLE
Encoding CompatibilityError

### ISSUE THREAD

**Issue by i-zhivetiev** [wincent/command-t#130]
Hello, I’ve got an issue: when I try to list files in the directory which contains non-english filenames, I get the error, while 1.11 works just fine.
![screenshot](https://cloud.githubusercontent.com/assets/2833663/4948823/f92a5a66-66ab-11e4-909b-b383ea88f0a1.png)
MacVim, Mac OS X 10.10, command-t 1.11.1-1.11.4
It’s a great plugin, really helpful, thank you.

**Comment by i-zhivetiev** [comment]
Thanks! It works fine.
> Command-T won't be very useful for actually finding files with non-ASCII characters in the names
It's not a big problem. It's not unusual to use ASCII characters in the filenames.

**Comment by wincent** [comment]
Even though this is super edge-casey, the impact of including the patch is low, so I just merged it to the `next` branch.
