### ISSUE TITLE
include .gitignore contents in the ignored files

### ISSUE THREAD

**Issue by benzen** [wincent/command-t#142]
When using git or any other SCM, we have files to say that we want to scm ignore certain path/files.
It would be nice to also ignore thoses path using CmdT

**Comment by octref** [comment]
@benzen 
Just come across this issue by accident. 
I wrote a vim plugin that parses gitignore and set 'wildignore', which Command-T uses to filter its output. Might help you here. [octref/RootIgnore](https://github.com/octref/RootIgnore)

**Comment by wincent** [comment]
Cool, thanks for sharing @octref.

**Comment by dylan-chong** [comment]
Seems like this should be closed? Btw what ended up being the best solution?

**Comment by wincent** [comment]
@dylan-chong: Yeah, it probably can be closed. If you want this behavior, either use the Git scanner (as described in the docs), or use the plug-in that @octref mentioned.

Command-T could of course support this natively if anybody cared to implement it, but it's not a useful feature to me personally nor do I see much demand for it, so I won't be working on it. If somebody else wants to submit a PR for it thought that will be fine.

**Comment by image357** [comment]
There is a pull request that could handle that:
https://github.com/wincent/command-t/pull/313
