### ISSUE TITLE
make clean needed

### ISSUE THREAD

**Issue by binbrain** [wincent/command-t#144]
My version of Ruby was upgraded to 2.2.0 and it required I recompile command-t. Rerunning below commands seemed to work. No errors.
[binbrain@darsek command-t]$ ruby extconf.rb 
checking for float.h... yes
checking for ruby.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for pthread.h... yes
creating Makefile
[binbrain@darsek command-t]$ make
linking shared-object ext.so

However, when opening vim and using command-t vim crashed with the below error.
undefined symbol: rb_gc_writebarrier_unprotect_promoted

Quickly figured out that a simple make clean before make was needed.
[binbrain@darsek command-t]$ make clean
[binbrain@darsek command-t]$ make
compiling ext.c
compiling matcher.c
compiling match.c
linking shared-object ext.so

Mentioning that a make clean might be required before the make in the Install Readme could be helpful to others that run into this. Thanks.

**Comment by wincent** [comment]
Yeah, it's probably worth adding to the troubleshooting section of the documentation.
