### ISSUE TITLE
Traverse submodules when using TFileScanner="git"

### ISSUE THREAD

**Issue by mathstuf** [wincent/command-t#147]
When in a repository with submodules, command-t doesn't look in submodules but instead just stops. It would be nice if command-t detected submodules and did `git ls-files` within them as well.

**Comment by wincent** [comment]
Yeah, that sounds reasonable, although it also sounds like the kind of thing that should probably be controllable via a setting.

`git-ls-files` doesn't have a `--recurse-submodules` option itself, for obvious reasons, so we'd have to issue a separate call to `git submodule status --recursive` and then run `git ls-files` in each of the found submodules.

I don't use the Git filescanner myself, so I am probably not going to get to this in the near future, but if you'd like to take a crack at it in the meantime I'd be happy to review a pull request.

Thanks for submitting the request!

**Comment by mathstuf** [comment]
I'm not personally a fan of submodules, but one repo at work uses it and the lack of it has been annoying enough lately. I'll see if I can hamfist my way through enough Ruby to get it done sometime this week or next.

**Comment by wincent** [comment]
Now on the `next` branch.
