### ISSUE TITLE
Error: commandt#CommandTShowFileFinder - LoadError: cannot load such file -- command-t/ext

### ISSUE THREAD

**Issue by nicolaiskogheim** [wincent/command-t#152]
Running `<leader>t`gives me this
![Screen dump of terminal when encountering error](https://www.dropbox.com/s/cvvpzstio3uhqw2/Screenshot%202015-02-18%2020.23.12.png?dl=1)

I believe that the file in the image is the one that throws the error. If I alter the argument to require, then the error message reflects that.
[finder.rb](https://github.com/wincent/command-t/blob/master/ruby/command-t/finder.rb)

It happened earlier today, worked like a charm yesterday.
I update my plugins regularly.
Tested with all plugins disabled.

Interestingly enough, the last commit affecting that very file was a change regarding that require statement. d8bf8ca19832c4d38a8449b22e333409d7b66d65

**Comment by wincent** [comment]
(On phone so will be brief)

Usually a failure to require the extension (that's what that file is, the
compiled part of Command-T) indicates some sort of miscompilation.

When you updated, did you also recompile (ie. `ruby extconf.rb && make` in
the ruby/command-t subdirectory)? And are you sure you compiled using the
same version of Ruby that Vim itself links against?

**Comment by nicolaiskogheim** [comment]
1. I have not touched a single file myself. No recompiling that I am aware of. Should I?
1.b But, I did change plugin manager, uninstall everything, and reinstall, with the manager.
So maybe the answer is yes, after all.
2. No, I'm not. My system, OSX, has ruby 2.0.0-p481, but :vim version only says -lruby 2.0.0


Should I build a fresh Vim? This was a brew build

**Comment by wincent** [comment]
I'd only re-build Vim as a last resort. I'd just try rebuilding Command-T first.

```
cd ~/.vim/bundle/command-t/ruby/command-t # or wherever you have it
make clean
ruby -e 'puts "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"' # make sure it says 2.0.0
ruby extconf.rb
make
```

If you're using rbenv, check to see what `rbenv versions` says... is it using the system Ruby? It probably should, because it seems likely that's the version of Vim that Homebrew used when building Ruby for you.

Finally, if you changed the bundle location at all while changing plug-in managers, make sure the old files are well and truly gone.

**Comment by nicolaiskogheim** [comment]
Thank you! All is well in vim land again.

Report:
```sh
$ make clean
make: *** No rule to make target `clean'.  Stop.

$ pwd # better check
/Users/nicolai/.vim/plugged/command-T/ruby/command-t #yep, should be right

$ rake clean # did this on reflex
(in /Users/nicolai/.vim/plugged/command-T)

 $ ruby -e 'puts "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"'
2.0.0-p481

$ ruby extconf.rb
checking for float.h... yes
checking for ruby.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for fcntl.h... yes
checking for stdint.h... yes
checking for sys/errno.h... yes
checking for sys/socket.h... yes
checking for ruby/st.h... yes
checking for st.h... yes
checking for pthread_create() in -lpthread... yes
creating Makefile

$ make
compiling ext.c
compiling match.c
compiling matcher.c
compiling watchman.c
linking shared-object ext.bundle

$ vim # SUCCESS
```
