### ISSUE TITLE
Previous search query

### ISSUE THREAD

**Issue by dymv** [wincent/command-t#153]
Is there a way to quickly retype previous search query to the Command-T window? Sometimes queries are too long to retype them every time and it'd handy to be able to quickly place previous one or even be able to go back through search history. What do you think?

**Comment by wincent** [comment]
There's not way to do this currently, but I'd be open to a pull request for it. If you were going to implement this, it is probably worth doing it more generally as a history stack than just a single "previous search entry".

**Comment by dylan-chong** [comment]
Just thinking: What about shortcuts (search backwards, forwards) for:

- `Tab and S-Tab`
- `C-e and C-y`

**Comment by wincent** [comment]
What’s your mnemonic for those?

**Comment by dylan-chong** [comment]
Not sure. In bash/vim command mode you can use up/down arrows for looking at the history, but in command t that moves around the list of files. I was trying to look for pairs of keys:

- `Tab and S-Tab` is for used autocompleting in ides/supertab
- `C-e and C-y` is for moving the screen up/down in vim

these are just thoughts, there are probably better options.

**Comment by wincent** [comment]
Another possibility is `C-r` (reverse history search) `C-s` (forward history search) as used in shells like Bash.

**Comment by nirajgup** [comment]
+1 for this feature

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
