### ISSUE TITLE
option delete

### ISSUE THREAD

**Issue by joseramonc** [wincent/command-t#154]
Hi, I'm new to vim so I'm sorry if I'm wrong, but I was expecting to be able to delete a word (until previous `/`) when I press <kbd>option</kbd> + <kbd>delete</kbd> on macvim but It don't go backward. Am I missing something or is there a way to configure it to do it?

**Comment by wincent** [comment]
I believe you can probably use the `g:CommandTClearPrevWordMap` setting for that; it defaults to `CTRL-w`.

https://github.com/wincent/command-t/blob/13760a725779b65fa0f2ebef51806f3c05a52550/doc/command-t.txt#L874-875

You could try adding `<A-Left>` to the map:

```
let g:CommandTClearPrevWordMap = ['<A-Left>', '<C-w>']
```

**Comment by joseramonc** [comment]
Thanks for your help, that setting and map did the trick.
