### ISSUE TITLE
CommandT ignoring static folder?

### ISSUE THREAD

**Issue by florida-elago-hs** [wincent/command-t#155]
Is it a default the static folder is getting ignored? and is there a way to make sure it isn't ignored? Thanks!

**Comment by florida-elago-hs** [comment]
Nvm i managed to configure the commandtwildignore.

**Comment by wincent** [comment]
No it is not ignored by default. If you're using default settings then the
ignored paths are coming from Vim's 'wildignore' setting.

Another possibility is that you have too many files (or a circular symlink)
and either need to increase g:CommandTMaxFiles or fix the symlink.

See the docs for more info on these.
