### ISSUE TITLE
Mark and multi-open feature

### ISSUE THREAD

**Issue by octref** [wincent/command-t#156]
Hey, I'm wondering if you could add a mark/multi-open feature,  similar to Ctrl-Z in ctrlp.

After a search, I want to mark multiple files and open them together. 
I went through the doc but can't find a way to do that.

**Comment by wincent** [comment]
Can you describe in a bit more detail what the desired behavior is? I'm not familiar with ctrlp, so I don't now how it works.

The closest thing in Command-T at the moment is the ability to move the matching file list into the quick fix window, with `<c-q>`.

**Comment by octref** [comment]
Sure!
Say I typed `foo`, and it returns 3 hits:

```
> foo.js
  foo-bar.js
  foo-baz.js
```

and now I want to open both `foo.js` and `foo-bar.js`.

If I have `<C-Z>` as `Mark`, I'd use `<C-Z>` to select `foo.js`, `<C-J>` to go to `foo-bar.js`, and `<C-Z>` again to select `foo-bar.js`. Now I hit enter and `foo.js` and `foo-bar.js` should be opened in two buffers.  

I don't really care which buffer would be active.  

This is pretty useful when you type a long query and want to open multiple hits, to avoid typing in the long query again.  
I guess #153 could also benefit from this. @dymv seems to be in the situation I described above.

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
