### ISSUE TITLE
Pressing `tab` while running `CommandT` hangs (looping on `(eval):3:in 'toggle_focus'`)

### ISSUE THREAD

**Issue by derenio** [wincent/command-t#157]
After pressing `tab` (while in the "`CommandT` mode") the vim hangs with a screen of these messages:
```
(eval):6:in `take'
(eval):6:in `rescue in toggle_focus'
(eval):3:in `toggle_focus'
(eval):3:in `toggle_focus'
...
```
I've checked tag `1.11.4` and it works there just well.

**Comment by wincent** [comment]
Cool. Thanks for the report. This is a regression and fortunately I can repro it.

**Comment by wincent** [comment]
I'm going to cut a new release for this, so marking this as closed. Thanks once again for the report.
