### ISSUE TITLE
CommandT search crashes vim 7.4.712 with many directories

### ISSUE THREAD

**Issue by PVince81** [wincent/command-t#160]
My distro (openSUSE Factory) updated to vim-7.4.712-1.2.x86_64 recently, and since then running the Command-T search crashes vim with the following message:
```
Vim: Caught deadly signal SEGV
```

Sometimes it also fails with:
```
Vim: Double signal, exiting
```

I tried recompiling the Ruby module (make clean; make), but the problem still persists.

Here is the vim debug log: https://owncloud.vincentpetry.net/index.php/s/oEsAvq5Z5dD13nY

I noticed that this only happens when running command-t on the owncloud source code which has many directories and subdirectories. It works properly with smaller projects.

Maybe the new vim version has added or reduced the limit of folder recursion ?

**Comment by PVince81** [comment]
The previous vim version that worked was 7.4.694

**Comment by Shougo** [comment]
Your ruby interface works?
`:ruby print('hello')`

**Comment by wincent** [comment]
> Maybe the new vim version has added or reduced the limit of folder recursion?

No, even if this were the case, Command-T isn't asking Vim to do any recursion. If you're using the default file scanner, then the traversal is happening in Ruby, and if you're using another scanner (like Watchman or Git) then the scanning is delegated to an entirely different process.

I think recompiling was the right thing to try. I suspect that whatever version of Ruby you compiled with is not the one that your distro's Vim links against. (Either that or there's some other architectural difference, like 32-vs-64-bit.)

What's the output of `:ruby puts "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"` in your new Vim? And what's the output of `ruby -e 'puts "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"'` on the command line where you built Command-T?

**Comment by PVince81** [comment]
I managed to make it work again: I actually uninstalled the extension with vundle, then reinstalled.
I had to rerun `ruby extconf.rb` (which I didn't do previously, I only did `make clean; make`).

It seems to have solved the problem.
Also I read somewhere that openSUSE Factory had recently updated Ruby to 2.2, so it might indeed be a version mismatch issue.

This is what I get now:
`:ruby puts "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"` gives `2.2.2-p95`
Same on the command line.

I wonder if it would be possible for command-t (or any ruby extension) to detect the version mismatch and print an error message instead. But it might not be worth the hassle :smile: 

Feel free to close this as PEBCAK :wink:

**Comment by wincent** [comment]
There is code that (attempts to) do this in recent versions of Command-T.
But it only works if you run `extconf.rb`.

Glad you got it sorted out!

**Comment by asm** [comment]
Hrm, I'm having this issue as well with f7344ebb.  Here are the details of my env:

```
vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 19 2015 11:43:42)
MacOS X (unix) version
Included patches: 1-712
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /usr/bin/clang   -L. -L/usr/local/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/Cellar/python/2.7.9/Frameworks -framework Python   -lruby.2.0.0 -lobjc
```

Here's the version of ruby I'm using to run ```ruby extconf.rb```
```
ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

Which matches the version vim was compiled with: ```2.0.0-p481```.  I've also tried fiddling with ARCH_FLAGS but nothing seems to work.  ```:CommandTFlush``` works but ```:CommandT```doesn't :sob: 

Shall I send along a backtrace?

**Comment by wincent** [comment]
No, I don't think a backtrace will be helpful, as this is probably a miscompilation rather than a bug.

You did well in comparing the Ruby versions, but something else is up. I would try uninstalling Vim and rebuilding both it and Command-T. Beyond that, I am not sure.

**Comment by wincent** [comment]
Guess I am going to close this due to inactivity.
