### ISSUE TITLE
Always shows same list of files

### ISSUE THREAD

**Issue by adamski** [wincent/command-t#161]
I've just installed Command T and it seems to be stuck on the same file listing, on ```<Leader>t```. 
I've tried changing ```g:CommandTTraverseSCM``` to ```pwd``` or ```dir```, and tried ```CommandTFlush``` but still get the same file list.

**Comment by wincent** [comment]
You would see this with `pwd`, for example, if you don't ever change Vim's current working directory (ie. what you see when you type `:pwd` in Vim). Similarly, you'd see it with `dir` if you never change Vim's working directory, or with `file` (the default) if all the files you edit are inside the same repo.

**Comment by adamski** [comment]
What I'm seeing, with just one project (the main project I'm working on), it will only show files from the first sub-directory. In this case its a web project, and the listing looks like this
```
> bower.json                                                                                                                                                                                                      
  bower_components/Chart.js/CONTRIBUTING.md
  bower_components/Chart.js/Chart.js
  bower_components/Chart.js/Chart.min.js
  bower_components/Chart.js/LICENSE.md
  bower_components/Chart.js/README.md
  bower_components/Chart.js/bower.json
  bower_components/Chart.js/docs/00-Getting-Started.md
  bower_components/Chart.js/docs/01-Line-Chart.md
  bower_components/Chart.js/docs/02-Bar-Chart.md
  bower_components/Chart.js/docs/03-Radar-Chart.md
  bower_components/Chart.js/docs/04-Polar-Area-Chart.md
  bower_components/Chart.js/docs/05-Pie-Doughnut-Chart.md
  bower_components/Chart.js/docs/06-Advanced.md
  bower_components/Chart.js/docs/07-Notes.md
  bower_components/Chart.js/gulpfile.js
  bower_components/Chart.js/package.json
  bower_components/Chart.js/samples/bar.html
  bower_components/Chart.js/samples/doughnut.html
  bower_components/Chart.js/samples/line-customTooltips.html
```
and it will only show me files from within the bower_components folder. Could it be that there are too many files and I need to increase one of the settings?

**Comment by adamski** [comment]
I set ```let g:CommandTFileScanner = 'git' ``` and it now works as expected... not sure what was going on there.

**Comment by adamski** [comment]
Just want to say thanks for a great plugin, really helping my workflow now, esp with the MRU buffer set to ```<C-b>```

**Comment by wincent** [comment]
Cool, glad to hear you got it sorted out.

Your theory about having too many files is likely correct. You can up the limit from the default of 30,000 by setting `g:CommandTMaxFiles` to something higher.

Another thing you can do is ignore the contents of directories like `bower_components`, `node_modules` etc, which usually aren't what you're looking for. For example, here are some of the settings I use for this purpose:

```
let g:CommandTWildIgnore = &wildignore
let g:CommandTWildIgnore .= ',**/.git/*'
let g:CommandTWildIgnore .= ',**/.hg/*'
let g:CommandTWildIgnore .= ',**/bower_components/*'
let g:CommandTWildIgnore .= ',**/node_modules/*'
let g:CommandTWildIgnore .= ',**/tmp/*'
```

See the docs for more info on the relationship between `'wildignore'` and `g:CommandTWildIgnore`.
