### ISSUE TITLE
Missing loading message on large directories

### ISSUE THREAD

**Issue by jsenin** [wincent/command-t#169]
Hi !
I'm a newbie in command-t. At first time I loaded :CommandT plugin from my home dir it's took too much time and I though that my vim was hangup, but was searching or caching files from my home dir, and I didn't know. 

So it's possible to show some message while plugin is searching ?

thanks

**Comment by wincent** [comment]
Yes, this is a good idea.

**Comment by wincent** [comment]
Added this a while back, so going to close.
