### ISSUE TITLE
Ruby-2.x compatibility

### ISSUE THREAD

**Issue by powerman** [wincent/command-t#171]
I'm using Gentoo Linux, and ruby-1.9 was removed from Gentoo portage few days ago. Currently installed versions are 2.0.0_p645 and 2.1.6, and looks like command-t fail to compile with these ruby versions (I've tried 1.13 and e0eaac7).

```sh
$ eselect ruby list 
Available Ruby profiles:
  [1]   ruby20 (with Rubygems) *
  [2]   ruby21 (with Rubygems)
$ ruby extconf.rb 
checking for float.h... yes
checking for ruby.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for fcntl.h... yes
checking for stdint.h... yes
checking for sys/errno.h... yes
checking for sys/socket.h... yes
checking for ruby/st.h... yes
checking for st.h... yes
checking for pthread_create() in -lpthread... yes
creating Makefile
$ make
linking shared-object ext.so
watchman.o: In function `watchman_load':
watchman.c:(.text+0xc96): undefined reference to `rb_float_new'
collect2: error: ld returned 1 exit status
Makefile:231: recipe for target 'ext.so' failed
make: *** [ext.so] Error 1

$ eselect ruby list 
Available Ruby profiles:
  [1]   ruby20 (with Rubygems)
  [2]   ruby21 (with Rubygems) *
$ ruby extconf.rb 
checking for float.h... yes
checking for ruby.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for fcntl.h... yes
checking for stdint.h... yes
checking for sys/errno.h... yes
checking for sys/socket.h... yes
checking for ruby/st.h... yes
checking for st.h... yes
checking for pthread_create() in -lpthread... yes
creating Makefile
$ make
linking shared-object ext.so
watchman.o: In function `watchman_load_array':
watchman.c:(.text+0xd53): undefined reference to `rb_ary_new2'
watchman.o: In function `watchman_load_template':
watchman.c:(.text+0xed8): undefined reference to `rb_ary_new2'
watchman.c:(.text+0xf1a): undefined reference to `rb_ary_new2'
collect2: error: ld returned 1 exit status
Makefile:232: recipe for target 'ext.so' failed
make: *** [ext.so] Error 1
```

**Comment by wincent** [comment]
I'm using Command-T with Ruby >= 2.0, so it should work. Did you do a `make clean` to clean up the state from your prior install before doing `ruby extconf.rb && make`?

**Comment by powerman** [comment]
Thanks, `make clean` solve issue.

BTW, is there any reason why Command-T doesn't automatically run `make clean && ruby extconf.rb && make` when it fail to load part of it vim plugin? If this isn't possible then it might make sense to add some shortcut for these 3 commands in top-level Makefile.

**Comment by wincent** [comment]
> is there any reason why Command-T doesn't automatically run `make clean && ruby extconf.rb && make` when it fail to load part of it vim plugin?

That would be a very scary thing to do automatically, given that it mutates — possibly destructively — the filesystem. And given that people can do crazy, uncontrolled things in their environments (such as have multiple Ruby and/or Vim installs, and switch around among them) it makes doing this sort of thing in an unsupervised way even more scary. So, I'd strongly bias towards providing better diagnostic information and tips, and better documentation. Let me know if you have any ideas for either of those things.

As for adding commands to the `Makefile`, we could to that, but it's not mentioned anywhere in the docs (it was really only ever intended for development purposes), so it might not be so discoverable. It's worth thinking about though. Let me think about it.

**Comment by wincent** [comment]
FWIW I just removed the `Makefile` in 752ba5515b322a13999 to avoid confusion.

The `Rakefile` already has a `make` task that does a pre-emptive `clean` as a preliminary step. Perhaps just documenting this better is the solution.

**Comment by powerman** [comment]
BTW, what other people does in similar cases? I've about 30 vim plugins installed, but only one which needs unusual (for vim plugins) actions to be done from time to time to keep it working is Command-T.

**Comment by wincent** [comment]
It's unfortunate, but:

- Command-T's prime goal is to be performant on large projects
- So it needs to have a part that's written in C
- Which means it needs a compilation step
- And the way to get a C extension into Vim is to embed it using one of the scripting interfaces like Ruby or Python
- So Command-T needs a Vim built with Ruby support
- And the version of Ruby used to build Command-T must exactly match the version of Ruby that Vim itself was linked against
- But people are in the habit of switching Ruby versions all the time, and many use version managers that enable them to switch on a per-directory or per-project basis
- So, chaos ensues and it is very easy to miscompile or break Command-T

I wish things weren't like this, but the only way to make installing and upgrading easier would be to drop Ruby and therefore C, which would compromise the primary design goal of the project.

I do have a long-term interest in trying to rearchitect all this as a separate daemon, and Vim could talk to it through a pure Vimscript plug-in (or at least a Ruby/Python plug-in without a compiled component), but it is not clear whether it would be much better. It would be trading one set of problems for another, as you'd still need to compile the daemon, and keep it running. Maybe one day...

**Comment by Shougo** [comment]
Oh, neovim solves the problem I think.
But current neovim does not support if_ruby...
