### ISSUE TITLE
git://git.wincent.com/command-t.git: read error: Connection reset by peer

### ISSUE THREAD

**Issue by powerman** [wincent/command-t#172]
Looks like original repo isn't working. Is github mirror now should be used as main repo?

**Comment by wincent** [comment]
Feel free to point at the GitHub repo; it's always kept in sync.

I'll give the other repo a kick. Thanks for letting me know about the issue.

Annoying that my monit monitoring does't actually alert me when this happens...

**Comment by wincent** [comment]
I manually revived the server. FWIW, [here's the ticket](https://wincent.com/issues/1909) I have to track improving the monitoring situation.
