### ISSUE TITLE
Search gets stuck in git submodules

### ISSUE THREAD

**Issue by mkeeter** [wincent/command-t#173]
Given the following directory structure:
```
.
├── .git
│   ├── ...
├── a
├── b
└── sub
    ├── .git
    │   ├── ...
    ├── c
    └── d
```
(where `sub` is a git submodule)

I can use command-t to open any file initially.  However, if I use command-t to open `c`, future searches will be unable to find `a` or `b`, so I suspect it gets stuck in the submodule.

**Comment by wincent** [comment]
This is probably the result of the `g:CommandTTraverseSCM` setting (see `:h g:CommandTTraverseSCM`).

It defaults to `"file"`, which causes Command-T to look for the closest SCM root relative to the currently-edited file. `"dir"` or `"pwd"` may suit your preferences better, however.

I'm going to close this one, but feel free to comment if you have any other thoughts or suggestions.

**Comment by mkeeter** [comment]
Okay, changing that setting makes it work as expected.

Would you be open to a PR that changes `file` mode to use the top-level SCM root, escaping out of submodules (at least for `git`)?

**Comment by wincent** [comment]
Sure, but I think it should actually be a separate mode, because some
people might like the existing behavior.
