### ISSUE TITLE
Request: modify a git-ignored file in extconf.rb

### ISSUE THREAD

**Issue by lencioni** [wincent/command-t#174]
af62f93c added some code to `extconf.rb` that modifies `ruby/command-t/metadata.rb` for installation diagnostics. Because these changes are not tracked by source control, it will cause people who use Command-T as a git submodule without the ignore dirty option to see the submodule as dirty after installation. It would be a little nicer if this instead created a file that was listed in the `.gitignore` file.

**Comment by wincent** [comment]
Yeah, this was initially my intent (note that the `metadata.rb` file _is_ in the `.gitignore` file in af62f93), but `.gitignore` only prevents an untracked file from becoming tracked; it doesn't make Git blind to changes in a tracked file.

I think we can make this work. Let me look into it.

**Comment by wincent** [comment]
I think 09af65e5b8a (on the `next` branch) should fix this. Let me know if it doesn't.

Thanks once again for the report!
