### ISSUE TITLE
Switching buffers with CommandTBuffer always goes to line 1

### ISSUE THREAD

**Issue by aapiskukko** [wincent/command-t#176]
When I switch buffer with Vim builtin :b command, I go straight to the line I was before leaving the buffer. But when I change buffer with Command-T plugin's CommandTBuffer it always goes to the line 1 of the changed buffer.

Is there a way to get buffer changing working with Command-T similar as with the builtin :b command?

**Comment by wincent** [comment]
This doesn't happen for me. I wonder if you have an autocommand that is causing the cursor to move (or alternatively, whether it's me who has an autocommand that does move it to the right place for me).

You might need to set something up as described in `:h last-position-jump` (I have this).

**Comment by aapiskukko** [comment]
Uncommenting that last-position-jump seemed to help. Thanks!

**Comment by wincent** [comment]
Great. I'll close this then.
