### ISSUE TITLE
 Support GNU readline keyboard shortcuts in file name prompt

### ISSUE THREAD

**Issue by rr-** [wincent/command-t#180]
When I search for the file to open, I'd like to use GNU readline's hotkeys such as

- <kbd>Alt</kbd>+<kbd>B</kbd> - navigate to previous word
- <kbd>Alt</kbd>+<kbd>F</kbd> - navigate to next word
- <kbd>Ctrl</kbd>+<kbd>A</kbd> - navigate to start of line
- <kbd>Ctrl</kbd>+<kbd>E</kbd> - navigate to end of line
- <kbd>Ctrl</kbd>+<kbd>W</kbd> - delete last word

etc. These prove to be really handy in other applications, and they're supported pretty much everywhere: zsh, bash, vifm, vim's ctrl+p (partially), vimperator (partially), most of my interactive scripts (even though they're written in Python and I didn't try to make them support such hotkeys)...

Personally, the most important for me is ability to easily navigate back. Suppose I have bunch of files named the same way, whose only distinguishing feature is their namespace / directory they're stored in. Normally I don't remember that, so rather than typing `dir/example` I type just `example`, and thus I get random results. To clarify what `example` I wanted, I need to go all the way to the left using ← repeatedly and type a part of directory.

The usual way for all libreadline oriented programs is to either hit <kbd>Ctrl</kbd>+<kbd>A</kbd> or <kbd>Alt</kbd>+<kbd>B</kbd>. Half of the time, <kbd>Home</kbd> would suffice too, but in case of command-t, it doesn't work either. This, and my past experiences with terminal emulators, make me believe that libreadline shortcuts should be preferred to <kbd>Home</kbd>, <kbd>End</kbd>, <kbd>Ctrl</kbd>+<kbd>←</kbd>, <kbd>Ctrl</kbd>+<kbd>→</kbd> etc., because unlike the latter, they're well supported by most terminal emulators out of the box.

I created similar issue at scrooloose/nerdtree/issues/504. Perhaps you share some function to prompt the user for input, and this is a limitation of vim itself. Either way, it would be useful to have this around.

**Comment by rr-** [comment]
Looks like this can be solved through `.vimrc` alone:

    " make meta key work (this might be need to be specialized for other terms)
    " urxvt
    execute "set <M-b>=\eb"
    execute "set <M-f>=\ef"

    cnoremap <C-a> <Home>
    cnoremap <C-e> <End>
    cnoremap <C-p> <Up>
    cnoremap <C-n> <Down>
    cnoremap <C-b> <Left>
    cnoremap <C-f> <Right>
    cnoremap <M-b> <S-Left>
    cnoremap <M-f> <S-Right>

Note that <kbd>Alt</kbd>+<kbd>B</kbd> and <kbd>Alt</kbd>+<kbd>F</kbd> still do not work (despite working in regular command prompts) but this is a non-issue now that one can use <kbd>C</kbd>-<kbd>A</kbd>.

Answers on SO that helped me to resolve the issue:

- http://stackoverflow.com/questions/6920943/navigating-in-vims-command-mode
- http://stackoverflow.com/questions/7501092/can-i-map-alt-key-in-vim/27206531#27206531

**Comment by wincent** [comment]
Thanks for sharing your findings.
