### ISSUE TITLE
install instructions fails - no extconf.rb file

### ISSUE THREAD

**Issue by ikke-t** [wincent/command-t#181]
I tried installing this on Mac with macports. The install instructions tell to do:

  cd bundle/command-t/ruby/
  $ ruby extconf.rb
  ruby: No such file or directory -- extconf.rb (LoadError)

This fails due there is no such file in the original repository, thus the following make command fails too as there is no makefile.

**Comment by ikke-t** [comment]
duh, wrong dir...

**Comment by wincent** [comment]
@mayankesh-maurya: It depends on where you installed the plug-in. For example, if you installed it at `~/.vim/pack/bundle/start/command-t` then you would run it in `~/.vim/pack/bundle/start/command-t/ruby/command-t/ext/command-t`. (Note that this issue you're looking at is pretty old; the build files are now nested more deeply than before, at `<CommandT-root>/ruby/command-t/ext/command-t`, whereas they used to be at `ruby/command-t/ext`, IIRC.)
