### ISSUE TITLE
CommandTTag doesn't respect filename when jumping to tag

### ISSUE THREAD

**Issue by elricbk** [wincent/command-t#183]
For C++ project it is common to have multiple definitions of one tag (i.e. class and its constructor). When using `CommandTTagIncludeFilenames` option these tags are shown as different ones in list. For example:

```
MyClass:path/to/myclass.h <- this is a class
MyClass:path/to/myclass.cpp <- this is a function
```

But CommandT doesn't use information about file in its `TagFinder` class code. This leads to always jumping to the same location in the same file despite choosing different filenames in tag list.

There is another problem linked to this. There could be tags with same name but different meaning in same file:

```
    MyClass:path/to/myclass.h <- this is a class
    MyClass:path/to/myclass.h <- this is a function prototype (constructor declaration)
    MyClass:path/to/myclass.cpp <- this is a function (constructor definition)
```

Information about class/function prototype is lost in CommandT taglist.

**Comment by wincent** [comment]
Thanks for the report @elricbk. I don't actually use the `TagFinder` myself, so am not really in a position to develop any changes or test it. If you have any concrete suggestions for changes to the code, or want to make a PR for it, I'd be happy to look at it.

**Comment by Camouflager** [comment]
The way vim searches through tags is limited. It is documented that when jumping to a tag the current buffer is always used first. So I made this modification in `tag_finder.rb`.

```rb
      def open_selection(command, selection, options = {})
        filepath = nil
        if @scanner.include_filenames
          arr = selection.split(':', 2)
          selection = arr[0]
          filepath = arr[1]
          # selection = selection[0, selection.index(':')]
        end

        #  open the tag and center the screen on it
        if !filepath
          ::VIM::command "silent! tag #{selection} | :normal zz"
        else
          ::VIM::command "edit #{filepath} | silent! tag #{selection} | :normal zz"
        end
      end
```

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
