### ISSUE TITLE
Make cursor color configurable (to solve invisible prompt cursor when using Solarized color scheme)

### ISSUE THREAD

**Issue by elricbk** [wincent/command-t#184]
Some configuration info:
* Mac OS X 10.10
* iTerm with solarized colors
* `solarized` colorscheme

Default prompt's cursor is shown like black rectangle. CtrlP's cursor is shown like dark gray char underline. Switching to any of the default colorschemes enables showing the cursor. The problem persists both for light and dark `solarized` variants.

**Comment by wincent** [comment]
Thanks for opening the issue. This is using the "Underlined" higlight group (ie. `:hi Underlined`).

You could experiment with changing [this line here](https://github.com/wincent/command-t/blob/f7344ebbe95c532b2ad01f19877d6d611db0193b/ruby/command-t/prompt.rb#L120) to some other value, to see if you can find something that you like.

This is what "Underlined" looks like for me:

<img width="183" alt="screen_shot_2015-12-18_at_11_18_33_am_png" src="https://cloud.githubusercontent.com/assets/7074/11905255/3f37f582-a57a-11e5-8bdb-146854c7bdb4.png">

For some reason, "Cursor" doesn't show up, but others like "Error" do. On my system, "PMenuSel" is pretty close to "Cursor".

Anyway, try a few out and see which you like. I think we could definitely make the used color configurable, like [the highlight color already is](https://github.com/wincent/command-t/blob/f7344ebbe95c532b2ad01f19877d6d611db0193b/doc/command-t.txt#L772-L776).

**Comment by wincent** [comment]
I've added a `g:CommandTCursorColor` option which should address this (on the `next` branch), so I'm going to mark this as closed. Thanks once again for the report.

**Comment by elricbk** [comment]
Thanks, "StatusLine" highlight group did the trick for me.
