### ISSUE TITLE
Enabling &macligatures makes the input flicker and characters disappear

### ISSUE THREAD

**Issue by moll** [wincent/command-t#185]
Hey,

With the latest MacVim v7.4-87 and `set macligatures`, Command-T's text input field flickers after typing and characters disappear. Functionally, it works. Are you seeing this, too?

Cheers,

**Comment by wincent** [comment]
Thanks for the report, @moll. I can reproduce this, but I am not sure there's much I can do about it. Might be worth reporting upstream that the flicker is happening with a plug-in that does a lot of updates via `echon`. Specifically, you can see [in the code](https://github.com/wincent/command-t/blob/978c0a6bbd8a318023a19787f95cc2041c614db6/ruby/command-t/prompt.rb#L117-L160) that we're basically doing this sequence for each keypress to update the prompt area:

```
:redraw
:echohl SomeHighlight
:echon "> foo"
:echohl None
```

I don't think there is anything actionable for me here, so I am going to mark this one as closed. Please feel free to comment though if you have any further thoughts.

**Comment by moll** [comment]
Hmm, I don't know how to report this to https://github.com/macvim-dev/macvim unfortunately as I don't know how to minimally reproduce it. Any ideas? 

The following function does not exhibit this problem:
```vim
function! Lig(s)
	new
	redraw
	echohl WarningMsg | echon a:s | echohl None
endfunction
```

**Comment by wincent** [comment]
If you look at the code I linked to above you'll see that it is emitting multiple segments with different highlighting applied (ie. a `>>` prompt with `Comment` highlighting applied, then text with `None` highlighting and a section with `Underlined`  highlighting to show where the cursor is), so your repro recipe may need to involve multiple highlights.

**Comment by moll** [comment]
Thanks for hint! I might or might not debug this further this month. Dinner sounds more appealing. ^_^
