### ISSUE TITLE
Update to RSpec 3.x syntax.

### ISSUE THREAD

**Issue by voxik** [wincent/command-t#190]
We are trying to use RSpec 3.x wherever we can in Fedora and there is lying RSpec 3 patch [1] in Fedora's repository already for some while. I though you might be interested in it. No PR, since I am not the author.

[1] http://pkgs.fedoraproject.org/cgit/rpms/vim-command-t.git/plain/vim-command-t-1.10-support-Rspec-3-style.patch

**Comment by voxik** [comment]
Actually there is still one deprecation warning remaining:

```
Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /builddir/build/BUILD/vim-command-t-2.0/spec/command-t/finder/buffer_finder_spec.rb:15:in `block (3 levels) in <top (required)>'.
```

But the patch was created to be as small as possible, just to let the test suite pass.

**Comment by wincent** [comment]
Thanks for the report @voxik. I split the deprecation warning off into a separate issue (https://github.com/wincent/command-t/issues/193), and pushed a commit to the `next` branch that fixes the issue with the `be_*` matchers, so I'll close this one.
