### ISSUE TITLE
QuickTime plugin on the sites screencast page is outdated

### ISSUE THREAD

**Issue by shvetsovdm** [wincent/command-t#194]

**Comment by wincent** [comment]
Thanks for bringing this up. I could replace the references to the QuickTime plug-in with HTML5 `<video>` tags, but...

...the screencast content itself is pretty outdated too, so I suspect this is probably not worth fixing. I am probably going to just redirect people to GitHub, make the GitHub README more of a "landing page" (and not just a link to the docs), and turn the https://wincent.com/products/command-t page into a redirect back here too.

**Comment by wincent** [comment]
- [ ] Remove references to wincent.com product pages.
- [ ] Redirect product pages to GitHub.
- [ ] Improve GitHub README.

**Comment by shvetsovdm** [comment]
@wincent  nice!
