### ISSUE TITLE
Could not load the C extension even after compiling

### ISSUE THREAD

**Issue by adamk33n3r** [wincent/command-t#196]
This is the error

```
command-t.vim could not load the C extension                                                                                                                                                               
Please see INSTALLATION and TROUBLE-SHOOTING in the help
Vim Ruby version: 2.3.0-p0
Expected version: [unknown]-p[unknown]
For more information type:    :help command-t
Press ENTER or type command to continue
```

Notice the `[unknown]`. That's weird. System ruby is `2.3.0-p0` as well. I tried running both `rake make` and going into the dir and running `ruby extconf.rb && make`

**Comment by wincent** [comment]
This is evidence of a mismatch between the version of Ruby used to build Vim and the one used to build Command-T. Updated your system Ruby or Vim lately?

Doing `ruby extconf.rb && make` was a good idea, but I think you'll likely need a `make clean` _first_ in there to get rid of whatever old version you likely have lying around there. Let me know how you go.

**Comment by adamk33n3r** [comment]
Interesting that my versions said they were the same in both vim and ruby but that it didn't like it. I previously had run a make clean which still didn't work. But i didn't expect it to since I didn't have any old version.

I rebooted my computer this morning and wanted to try again and it magically worked. I have no idea why this would have happened but it seems to be working fine now. Sorry for yet another issue about compilation.

**Comment by wincent** [comment]
No problem. Glad you got it sorted out.

**Comment by KLIM8D** [comment]
Just had the same issue, fixed this by executing the mentioned commands, 
> ruby extconf.rb && make 
inside "../command-t/ruby/command-t"

No reboot needed

**Comment by dlo** [comment]
I had the same issue (expected version displayed as `[unknown]-p[unknown]`), but my problem was that I didn't read the documentation and didn't compile the extension first. Figured I'd put this here for anyone else who gets here via search engine. :)

**Comment by kuon** [comment]
I had this issue while using [dein](https://github.com/Shougo/dein.vim) and neovim and after some frustration, I discovered that dein was caching the plugin, running `:call dein#recache_runtimepath()`  fixed the issue. This is unrelated to command-t, but I think it's good it's here for reference.

**Comment by wincent** [comment]
@kuon: Thanks for sharing. If you or anybody else wants to add this as a troubleshooting tip to the docs, please feel welcome to do so.

**Comment by mikeyduece** [comment]
Would it be a good idea to upgrade/change the vim ruby version to match that of the system ruby verson. My vim is using 2.0 and everywhere else I'm using 2.4.1. How hard would it be to change the vim ruby version instead? I'm super new to vim in general and saw this plugin and am stoked to give it a try. got really used to using it in atom .

**Comment by wincent** [comment]
@mikeyduece:

> Would it be a good idea to upgrade/change the vim ruby version to match that of the system ruby verson. My vim is using 2.0 and everywhere else I'm using 2.4.1. How hard would it be to change the vim ruby version instead? I'm super new to vim in general and saw this plugin and am stoked to give it a try. got really used to using it in atom .

In general, the only thing that really matters is that the versions match. Having a newer version won't unlock performance wins (the performance-critical sections are written in C) nor are there any features in later versions of Ruby that get leveraged to deliver new functionality.

The simplest thing is usually to let Vim link against the system Ruby, and build Command-T against the system Ruby too, even though the system Ruby may be quite old (that's the case with macOS, for example). This isolates you from the insanity that may be having multiple versions of Ruby active in different directories depending on the presence of `.ruby-version` files etc.

If you did want to use a different version, you can compile Vim yourself and link it against any version of Ruby that you please; in order for Command-T to work with it, you just have to make sure you build it against the same version.

FWIW, my policy with these things is "if it ain't broke, don't fix it"; so give a working set-up, I don't touch it.

**Comment by widian** [comment]
Now, path of extconf.rb is changed from ../command-t/ruby/command-t to ../command-t/ruby/command-t/ext/command-t 

I always find this issue via google and I compile it. Thanks for all contributors and especially for wincent.
