### ISSUE TITLE
Question: Easy settings for "split or goto, tabnew or goto"

### ISSUE THREAD

**Issue by jordwalke** [wincent/command-t#197]
Are there some easy to use settings in `command-t` for being able to map keyboard shortcuts to "vertical split or goto existing buffer if already exists in window", or "open in new tab or go to existing buffer if already exists in window"?

**Comment by wincent** [comment]
Nothing "easy" as such, although you can assign an arbitrary command to be used in response to any of the "open" mappings. For example, in my dotfiles I implement and use [a `GotoOrOpen` command](https://github.com/wincent/wincent/blob/907a63aebab77cd0c38528753f363c83b2d1b093/roles/dotfiles/files/.vim/after/plugin/command-t.vim#L23-L64). In conjunction with setting `'switchbuf'` to `usetab`, this might be close to what you're describing here.

**Comment by jordwalke** [comment]
That `GotoOrOpen` command would make a nice built in command for Vim, or a nice micro plugin (if only `Vim` package managers had `npm` style dependency installations).

**Comment by jordwalke** [comment]
@wincent Can I include `GotoOrOpen` in VimBox? It's not clear what the license is.

**Comment by wincent** [comment]
Consider it in the public domain. I should probably make that explicit.
