### ISSUE TITLE
On Ubuntu 12.04-64,ruby 1.8.7,Vim 7.4,can't load command-t

### ISSUE THREAD

**Issue by nathan-huang** [wincent/command-t#198]
After compiling and then typting :CommandT,Vim shows the following errors:
Error detected while processing /home/nathan/.vim/bundle/command-t/autoload/comm
andt.vim:
line  193:
SyntaxError: (eval):12: /home/nathan/.vim/bundle/command-t/ruby/command-t/contro
ller.rb:266: syntax error, unexpected ')'
Error detected while processing function commandt#FileFinder:
line    2:
NoMethodError: undefined method `show_file_finder' for nil:NilClass

Ubuntu version:
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.2 LTS
Release:	12.04
Codename:	precise

ruby version：
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]

Vim version:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 20 2016 12:10:26)
Included patches: 1-1143
Compiled by nathan@nathan
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm

**Comment by wincent** [comment]
Thanks for the report,@nathan-huang.

That's a very old version of Ruby you're running there. I wonder if that is why it is choking on the syntax on line 266. (I'm downloading and installing an old Ruby now to verify that.)

**Comment by wincent** [comment]
Bah, 1.8.7 is too old to install on this machine. Can you try removing the trailing comma right before the line that it's complaining about and let me know if that fixes it? If so, I'll patch it and cut a new release.

**Comment by nathan-huang** [comment]
Yes ,after removing two comma command-t will work well.As follow
nathan@nathan:~/.vim/bundle/command-t$ git diff .
diff --git a/ruby/command-t/controller.rb b/ruby/command-t/controller.rb
index b512ca0..03d5d16 100644
--- a/ruby/command-t/controller.rb
+++ b/ruby/command-t/controller.rb
@@ -262,7 +262,7 @@ module CommandT
         :limit          => match_limit,
         :threads        => CommandT::Util.processor_count,
         :ignore_spaces  => VIM::get_bool('g:CommandTIgnoreSpaces', true),
-        :recurse        => VIM::get_bool('g:CommandTRecursiveMatch', true),
+        :recurse        => VIM::get_bool('g:CommandTRecursiveMatch', true)
       )
       @match_window.matches = @matches
 
diff --git a/ruby/command-t/match_window.rb b/ruby/command-t/match_window.rb
index 663d7fb..3ad9894 100644
--- a/ruby/command-t/match_window.rb
+++ b/ruby/command-t/match_window.rb
@@ -51,7 +51,7 @@ module CommandT
           :topline  => view['topline'],
           :topfill  => view['topfill'],
           :leftcol  => view['leftcol'],
-          :skipcol  => view['skipcol'],
+          :skipcol  => view['skipcol']
         )
 
         # When creating a split for the match window, move the cursor to the

**Comment by nathan-huang** [comment]
Yes, it will works fine after removing the comma,not only in ruby/command-t/controller.rb,but also in ruby/command-t/match_window.rb.As follow
diff --git a/ruby/command-t/controller.rb b/ruby/command-t/controller.rb
index b512ca0..03d5d16 100644
--- a/ruby/command-t/controller.rb
+++ b/ruby/command-t/controller.rb
@@ -262,7 +262,7 @@ module CommandT
         :limit          => match_limit,
         :threads        => CommandT::Util.processor_count,
         :ignore_spaces  => VIM::get_bool('g:CommandTIgnoreSpaces', true),
-        :recurse        => VIM::get_bool('g:CommandTRecursiveMatch', true),
+        :recurse        => VIM::get_bool('g:CommandTRecursiveMatch', true)
       )
 
diff --git a/ruby/command-t/match_window.rb b/ruby/command-t/match_window.rb
index 663d7fb..3ad9894 100644
--- a/ruby/command-t/match_window.rb
+++ b/ruby/command-t/match_window.rb
@@ -51,7 +51,7 @@ module CommandT
           :topline  => view['topline'],
           :topfill  => view['topfill'],
           :leftcol  => view['leftcol'],
-          :skipcol  => view['skipcol'],
+          :skipcol  => view['skipcol']
         )

**Comment by wincent** [comment]
Thanks for reporting this and verifying the proposed fix works. I'll be pushing the new release shortly.
