### ISSUE TITLE
Hook for disabling other plugins.

### ISSUE THREAD

**Issue by jordwalke** [wincent/command-t#200]
Is there a hook that will be invoked before the window is shown, and after the window is closed?
In my case, I need such a hook to disable the "GoldenView" plugin (which tries to automatically perform layout of panes that messes up command-t).

I would execute `:DisableGoldenViewResize` before command-t, and `:EnableGoldenViewResize` after command-t window closes.

**Comment by wincent** [comment]
Sounds like a good idea. I've done this [in other plug-ins](https://github.com/wincent/ferret/blob/7a9f763db6bc10193eb23f57ae4793fa52a06e53/doc/ferret.txt#L322-L338) so may as well do it here too. I just pushed aff3834 to the `next` branch that adds `CommandTWillShowMatchListing` and `CommandTDidHideMatchListing` "User" autocommands.
