### ISSUE TITLE
Can I also set g:CommandTCursorColor and g:CommandTHighlightColor with syntax group configuration directly?

### ISSUE THREAD

**Issue by nathan-huang** [wincent/command-t#201]
As follow 
let g:CommandTCursorColor = 'ctermfg=180 ctermbg=NONE cterm=NONE guifg=#dda790 guibg=NONE gui=NONE'
rather than just the format for highlight link

**Comment by wincent** [comment]
No, it requires a highlight group name. You can define a group if you want.
