### ISSUE TITLE
Could add the feature for the match listing being scrollable (maybe duplicate of #191)?

### ISSUE THREAD

**Issue by nathan-huang** [wincent/command-t#203]
Currently we should adopt a "path-centric" rather than a "filename-centric" mentality to find the file.But could the match listing be scrollable just for quickly browsing?

**Comment by wincent** [comment]
I'd be open to accepting a PR for this if it didn't introduce too much complexity, and had well-defined behavior (may be tricky to get that right).

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
