### ISSUE TITLE
Colortheme question

### ISSUE THREAD

**Issue by LikiPiki** [wincent/command-t#211]
Hello, what the color theme tour use in this 
gif https://raw.githubusercontent.com/wincent/command-t/media/command-t.gif

**Comment by LikiPiki** [comment]
I find in your dotfiles

**Comment by LikiPiki** [comment]
Is it base16-ocean?

**Comment by wincent** [comment]
Yep, base16-ocean dark.

**Comment by LikiPiki** [comment]
Thanks a lot
