### ISSUE TITLE
Way to filter from files currently opened buffers

### ISSUE THREAD

**Issue by Svalorzen** [wincent/command-t#212]
Since command-t provides a way to look between buffers only, it would be nice if there was a way to remove buffer entries from files when looking to open new files (and thus buffers). This would prevent populating the list of files with entries which have already been opened, and present the user with a more condensed list which only contains files which have yet to be added to the opened buffers.

So if a user already knows it has opened a buffer, he will look in the buffers only; otherwise he will look in the unopened files only. Maybe an option?

**Comment by wincent** [comment]
I'd be willing to accept a PR that made this an option, as long as it didn't regress performance.

It's not the kind of thing I would use myself. I typical have anywhere between 10 and 200 buffers open, but I'm working in a repo with  over a million files, so filtering out less than 0.001% of the files wouldn't be super valuable to me.

**Comment by wincent** [comment]
Closing this one due to inactivity. Note that this possibility was mentioned as an idea on https://github.com/wincent/command-t/issues/107 — so if anybody wants to discuss it further, doing so over there is probably a good idea (to keep all the discussion in one place).
