### ISSUE TITLE
"command-t.vim could not load the C extension" with ruby 2.3.0-p0 on ubuntu 16.04

### ISSUE THREAD

**Issue by tarasmatsyk** [wincent/command-t#214]
I am trying to set up a command-t plugin and get a strange error:

 ```
command-t.vim could not load the C extension
Please see INSTALLATION and TROUBLE-SHOOTING in the help
Vim Ruby version: 2.3.0-p0
Expected version: 2.3.0-p0
For more information type:    :help command-t
```
vim version
``` 
-lruby-2.3
```

And I tried to recompile it.
``` bash
cd ~/.vim/bundle/command-t/ruby/command-t
ruby extconf.rb
make clean
make 
````
Do you have an idea of what is wrong here? I assume I do have different versions of 2.3.0 ruby but I have no idea how to find out where the issue comes from

**Comment by wincent** [comment]
Just to confirm, what's the output of `ruby --version`?

And how did you install Vim?

**Comment by tarasmatsyk** [comment]
@wincent,
`ruby --version` gives
`ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]`
Vim was installed using `sudo apt-get install vim`

**Comment by wincent** [comment]
```
Vim Ruby version: 2.3.0-p0
Expected version: 2.3.0-p0
```

So there is something fishy going on that the versions seem to match but Command-T is complaining about them not matching.

You could try short-circuiting [this check](https://github.com/wincent/command-t/blob/2d80b2e65cd690dd17c66fb52e5f9fb09700b1e7/autoload/commandt.vim#L161-L164) by deleting the file at `ruby/command-t/metadata.rb`. But it would be nice to know what's causing that conditional there to trigger.

**Comment by tarasmatsyk** [comment]
@wincent,
Is it possible to debug somehow the code you are referencing to?

metadata.rb contains
```ruby
  module Metadata
    EXPECTED_RUBY_VERSION = "2.3.0"
    EXPECTED_RUBY_PATCHLEVEL = 0
    UNKNOWN = false
  end
```

**Comment by wincent** [comment]
Well, it is probably throwing an exception on [one of these two lines](https://github.com/wincent/command-t/blob/2d80b2e65cd690dd17c66fb52e5f9fb09700b1e7/autoload/commandt.vim#L165-L166). Debugging Vim plug-ins is hard, so some crude logging is probably the most straightforward thing:

```
diff --git a/autoload/commandt.vim b/autoload/commandt.vim
index 05828dd..7331d54 100644
--- a/autoload/commandt.vim
+++ b/autoload/commandt.vim
@@ -218,7 +218,8 @@ ruby << EOF
     else
       $command_t = CommandT::Stub.new
     end
-  rescue LoadError
+  rescue LoadError => e
+    File.open('/tmp/log', 'a') {|f| f.puts e.inspect}
     load_path_modified = false
     ::VIM::evaluate('&runtimepath').to_s.split(',').each do |path|
       lib = "#{path}/ruby"
```

or something like that.

**Comment by tarasmatsyk** [comment]
now I see the error. 
FIle.open did not work, so I added
```
  rescue LoadError => e
    puts "-------"
    puts e
```
And here is result:
```
-------
cannot load such file -- command-t
-------
incompatible library version - /home/taras/.vim/bundle/command-t/ruby/command-t/ext
.so

```

**Comment by wincent** [comment]
> ps. I use rvm. Just in case this info is useful.

I'd try taking that out of the equation and (re-)build Command-T with the system Ruby (is that `rvm shell system`, from memory?). Failing that, I'd just blow everything away and build both Vim and Command-T in the same session using the same Ruby.

If you Google for "incompatible library version" you'll find a bunch of examples [like this one](https://github.com/brianmario/mysql2/issues/721) in various Ruby projects, all caused by compiling against the wrong version, or with the wrong headers etc.

**Comment by tarasmatsyk** [comment]
@wincent, ahh, I agree.
I will close the issue.

Wincent, thank you for time. I appreciate that.

**Comment by guilpejon** [comment]
@tarasmatsyk Did you managed to solve this? I'm facing the exact same issue.

**Comment by tarasmatsyk** [comment]
@guilpejon, nope, try to rebuild vim with the right version of python and ruby support. 
I decided to use another plugin as this one took too much time to configure each time I switch environment.

**Comment by wincent** [comment]
It is a pain to install, always has been. See #220 for work on mitigating that. (Happening slowly.) If you're working in a project large enough to make Command-T the only viable option, the you deal with the pain, otherwise, it depends on your levels of masochism.

**Comment by shiau** [comment]
I was running into this issue with `ruby 2.4.0p0`.  Taking RVM out of the equation by using `rvm system` instead of `rvm use 2.4.0`  fixed it.

**Comment by wincent** [comment]
Go Jeff @shiau!

**Comment by dagfinnr** [comment]
I got a similar problem after having installed (and deleted) neovim. I dealt with the version mismatch simply with `brew unistall ruby`. But it still doesn't work. This is the message:

```
command-t.vim could not load the C extension
Please see INSTALLATION and TROUBLE-SHOOTING in the help
Vim Ruby version: 2.0.0-p648
Expected version: 2.0.0-p648
For more information type:    :help command-t
```

I've tried all the fixes I could find. I have no idea what changes neovim may have effected to cause this.

**Comment by dagfinnr** [comment]
Come to think of it, I'm not 100% sure it was neovim, since I also upgraded to Sierra recently.

**Comment by wincent** [comment]
Yeah, @dagfinnr, so the error message is not super helpful in this case. It's only supposed to show "Expected version" if it is different from "Vim Ruby Version", so I am not sure why it's showing up. Commit 45c853cb34817ff14d1866551bf30ad35cbc4083 made that change on the "next" branch, but it hasn't made it back onto the "master" branch yet.

Reinstalling Ruby was a good try, but did you rebuild Command-T as well after that? (With a full `make clean` beforehand and re-running `ruby extconf.rb` and `make`?)

**Comment by dagfinnr** [comment]
Yes, I did that too. BTW, I didn't reinstall Ruby, I just got rid of the homebrew Ruby so it would use the system Ruby.

**Comment by vicheanak** [comment]
I got it working with `make clean` before `make`
