### ISSUE TITLE
Ctrl-S and Ctrl-V are processed by the tty driver in Mac terminal apps

### ISSUE THREAD

**Issue by symbiat** [wincent/command-t#216]
So the default mappings to open files is split and vsplit windows is `^s` and `^v` however these are processed by the tty driver so they never reach vim. I know the workaround for `^s` is to disable flow control but what about `^v`? I tried remapping my iTerm2 key settings so that Cmd-S and Cmd-V send hex code 13 and 16 but that doesn't work. I work with NERDTree and lots of split windows but right now I can only open horizontal splits  so not ideal. Just wondering how to get round this so can open in a vsplit window too.

**Comment by wincent** [comment]
I've never heard of `CTRL-v` being special. It has always worked for me out of the box.

What is your local environment? (`$TERM`, OS etc)

**Comment by wincent** [comment]
Another thought: `CTRL-V` obviously works in Vim and is not intercepted by the terminal driver, otherwise visual block mode wouldn't work.

**Comment by symbiat** [comment]
On UNIX-based systems, CTRL V is interpreted by the tty driver to mean, "do not interpret the next keypress". So for example, this allows you to paste control codes into documents, even things like CTRL C. Needlress to say, CTRL V doesn't open the current selection in a vertical split. Im using stock vim (7.3) on El Capitan (10.11.4).

**Comment by symbiat** [comment]
Ah I just realized something that might be important: Im running vim inside screen where $TERM is screen-256olor.

**Comment by wincent** [comment]
Repeating what I said before:

> `CTRL-V` obviously works in Vim and is not intercepted by the terminal driver, otherwise visual block mode wouldn't work.

I'd really like to know the answer to that.

This has worked for me for 6 years across multiple versions of OS X, Linux, Terminal.app, iTerm2, inside and outside of tmux. I've never seen it not work. Perhaps it is something specific to screen, which I have never really used seriously, or perhaps you have something weird with your `'timeout'`/`'ttimeout'`/`'timeoutlen'`/`'ttimeoutlen'` settings.

What happens when you try this outside of screen?

**Comment by symbiat** [comment]
I made sure iTerm2 didn't have any key mappings and can confirm that CTRL V works both inside and outside of screen, but CTRL S doesn't work anywhere Im running Vim 7.3 (stock El Capitan).

**Comment by wincent** [comment]
I'm a bit confused. You said:

> I know the workaround for `^s` is to disable flow control but what about `^v`?

But then:

>  can confirm that CTRL V works both inside and outside of screen, but CTRL S doesn't work

So, <C-v> works, but <C-s> does not. Adding `stty -ixon` to my `~/.zshrc` is how I disable flow control. How are you disabling it?

**Comment by symbiat** [comment]
Disabling flow control before starting my screen session seems to work.
