### ISSUE TITLE
Can't paste query in MacVim: "Cannot make changes, 'modifiable' is off"

### ISSUE THREAD

**Issue by sophiebits** [wincent/command-t#217]
If I open command-t in MacVim and try to paste a filename, it fails, saying

> Cannot make changes, 'modifiable' is off

The same thing happens if I try to paste using `<C-r>*`. (In insert mode, `<D-v>` is actually mapped to `<C-G>u<C-R><C-O>*`.)

Is there any way to make this work?

**Comment by wincent** [comment]
Good question! I am not sure. Works in the terminal, with and without bracketed paste mode, but I can repro what you're seeing in MacVim.

There *might* indeed be a way to intercept the paste in MacVim (via a mapping) and turn it into keystrokes (either via `feedkeys()` or by directly call some Command-T method to appending to the current search string. Don't know off the top of my head though.

**Comment by sophiebits** [comment]
I seem to get the same thing in the terminal with bracketed paste mode too. Not sure where I'm going differently.

**Comment by wincent** [comment]
Interesting. Terminal works for me (specifically iTerm) both locally and remote (over SSH) with and without tmux, always with bracketed paste mode active. What's your set-up (terminal app, `$TERM`, versions etc)?

**Comment by rahul342** [comment]
Being running into the same issue on MacVim. Any luck?

**Comment by wincent** [comment]
> Being running into the same issue on MacVim. Any luck?

Looks like the current input handling could be replaced with something based on `getchar()`. I suspect that would work in MacVim and in the terminal.

**Comment by wincent** [comment]
Finally fixed on the "pu" branch, so closing this. 😌
