### ISSUE TITLE
Add message when max files limit is hit

### ISSUE THREAD

**Issue by lencioni** [wincent/command-t#218]
I just spent a good amount of time troubleshooting a problem where command-t wasn't allowing me to match on a bunch of files in my project (specifically it seemed like anything outside of my app directory). After a lot of experimentation, I was able to determine that I had simply hit the default max number of files. I resolved this by adding `let g:CommandTMaxFiles=1000000` and adding a large generated directory to the command-t wildignore list.

I believe I would have saved some time troubleshooting if there would have been a clear message when the max number of files was hit. Ideally this message would include pointers on next steps to take to resolve the issue.

**Comment by wincent** [comment]
One problem is where to put the message. The match listing is really only built to show files, and the prompt area is a very fragile abstraction built on top of the message area (I'm not even sure of the exact name for it) which Vim has a penchant for clearing (or *not* clearing) at odd times. I guess I could abuse `input()` for this purpose, although it would be pretty jarring. I'd probably want to up the default limit to about 100,000 anyway, which would end up being enough to cover most toy projects, even those with ridiculous trees buried under `node_modules` and the like.

**Comment by wincent** [comment]
So I just merged something to `next` for this. Going to mark this as closed.

**Comment by lencioni** [comment]
Thanks for the fast response on this! 🍝

**Comment by lencioni** [comment]
Another thing that would have eased my pain a bit would be a "smarter" ordering of files that are indexed. In my particular case, I ended up with a new dot-directory that had a bunch of new files in it. If the file finder de-prioritized recursing into dot-directories until after non-dot-directories, I would have still had a mostly useful set of files to work with even though I had hit the limit.

**Comment by wincent** [comment]
Want to file a separate issue for that one?

**Comment by lencioni** [comment]
Done! #219
