### ISSUE TITLE
Use "smarter" ordering when scanning files

### ISSUE THREAD

**Issue by lencioni** [wincent/command-t#219]
In #218 I detailed some troubleshooting I recently did:

> I just spent a good amount of time troubleshooting a problem where command-t wasn't allowing me to match on a bunch of files in my project (specifically it seemed like anything outside of my app directory). After a lot of experimentation, I was able to determine that I had simply hit the default max number of files. I resolved this by adding let g:CommandTMaxFiles=1000000 and adding a large generated directory to the command-t wildignore list.

6d829fe helps by raising the default limit and 068a376 helps more by showing a warning when the limit is hit, which are both great. However, I thought of another thing that would have eased my pain a bit: using a "smarter" ordering of files that are indexed. In my particular case, I ended up with a new dot-directory that had a bunch of new files in it. If the file finder de-prioritized recursing into dot-directories until after non-dot-directories, I would have still had a mostly useful set of files to work with even though I had hit the limit.

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
