### ISSUE TITLE
Make Command-T run outside of Vim process

### ISSUE THREAD

**Issue by wincent** [wincent/command-t#220]
High level:
- Run "background" `commandtd` via Vim's new `job_start` feature, and communicate via a pipe.
- Vim-side parts to be rewritten in VimL, removing the brittle Ruby dependency (system itself still needs Ruby, but it can be any supported version).

Details:
- Currently thinking of using synchronous communication, to keep things simple, but some challenges presented (long scans and progress updates would ideally be asynchronous).

Problems to be solved:
- Current Ruby codebase has lots of `::VIM` and `CommandT::VIM` calls sprinkled through it; examples:
  - `ProgressReporter`, called from scanners. All of this stuff needs to be refactored so that as much of the finder/scanner code as possible can be re-used.
- In general, the interelationship between the `Finder` and `Scanner` hierarchies is a mess.
- For perf, must avoid sending large blobs back and forth: this means scanning should happen on daemon side, but this could be tricky for some scanner types (tags). For others, like the `BufferScanner` and so on, no real way around sending the paths over the wire.
- Backwards compatibility:
  - At runtime, still want to work using old model on older Vim.
  - At install-time, ideally keep same or similar install process (albeit simpler, with an `install` script), so as not to break packagers and other downstreams; but note that some structural reorganization is probably necessary and is already underway

**Comment by trotzig** [comment]
I'm interested in following your progress on this! There might be some learnings that we could make use of over at import-js. Ping @lencioni.

**Comment by wincent** [comment]
@trotzig Stuff I've done so far is on [the `next` branch](https://github.com/wincent/command-t/commits/next). Still very preliminary. Need to think some things through.

**Comment by wincent** [comment]
Probably made redundant by https://github.com/wincent/command-t/issues/380 &mdash; can always revisit once that is done, if need be.
