### ISSUE TITLE
Installing Command-T in cygwin

### ISSUE THREAD

**Issue by jordiFrei** [wincent/command-t#221]
I am trying to get Command-T for vim in my cygwin environment.

I download the plugin through pathogeon and I get an error when I try to compile the plugin:

/usr/share/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.

I believe that the error is that the installation tries to use ruby version 2.2.0 and vim is linked to 2.2.4 (which is the only ruby version installed in my system). Now, it seems I could install rvm to force the usage of version 2.2.4 but this is not so simple under cygwin because rvm is not part of the distribution.

I have no idea of ruby, but for me it is hard to understand why the check of the ruby version fails to get the installed version

Thank you very much in advance

**Comment by wincent** [comment]
I don't have access to a Windows machine for testing, so I'm going to have leave this one up to the community to help out with. Please let me know if you figure anything out, but I'm going to close this one here and suggest that you ask on http://superuser.com/ or http://stackoverflow.com/.

That said, I doubt that the mismatch in the version of Ruby is involved here. A mismatch would cause Command-T to not run inside Vim, but that's only *after* you've compiled it. Sounds like you haven't even been able to compile it yet. The error message explicitly says "You have to install development tools first", so I think you need to do something about that. Back when I last tried this on Windows, literally years ago, I [documented the tools I used](https://github.com/wincent/command-t/blob/7b1080664baaf5709abfcb2029bb70ba7aaee32d/doc/command-t.txt#L138-L144).

**Comment by Bothari** [comment]
Disclaimer: I am a hacker at best for Ruby, I was mostly guessing. I also had this exact same issue though (downloaded the plugin through Vundle), and I discovered I had to add this line at the top of command-t/ruby/command-t/extconf.rb

`require 'devkit'

Once I had done that, everything built as expected.

**Comment by jordiFrei** [comment]
Thanks for your help

Bothari, your solution did not help me

I finally found the issue, it was quite simple really. I only needed to install the package  libcrypt-devel

Perhaps you can add this to the documentation:

"In cygwin you will need to install the libcrypt-devel package"

**Comment by tieTYT** [comment]
@jordiFrei I was wondering, how did you get ruby support into vim?  When I type `:ruby 1` I get an error.
