### ISSUE TITLE
Searching only subdirectories 

### ISSUE THREAD

**Issue by vicngtor** [wincent/command-t#222]
Does Command-t have the option to only search within the subdirectory (rather than the entire git directory?) 

This is particular for source code browsing for books with each chapter as its own separate folder. (Example: https://github.com/PacktPublishing/Mastering-Flask)

**Comment by wincent** [comment]
Three main ways to do this:

1. Filter by including some chars from the path in your search string (eg. to search for `extensions.py` in chapter 11 you might type "11ext").
2. Use [`g:CommandTTraverseSCM`](https://github.com/wincent/command-t/blob/7b1080664baaf5709abfcb2029bb70ba7aaee32d/doc/command-t.txt#L775-L794) to anchor Vim to the current directory, and then `:cd` into the chapter directory (ie. this is the "pwd" setting).
3. Invoke Command-T using a path (eg. `:CommandT chapter_11`; note that if your path has spaces in it you need to escape those with `\`).
