### ISSUE TITLE
Persist file cache between sessions

### ISSUE THREAD

**Issue by Bothari** [wincent/command-t#224]
I can't find any way to make Command-T persist the file cache between Vim sessions. It takes about 30-40 seconds to rebuild the cache every time I start vim; which fortunately isn't that often, but it is still a little frustrating.

**Comment by wincent** [comment]
This is exactly the use case that the "watchman" scanner was built for (see `g:CommandTFileScanner` in the docs).

For example, I'm using it in a directory tree right now with 995k files and it takes 4 seconds from the time I type `vim` to being able to interact with the Command-T prompt.

So I'm going to close this for now as I don't plan on taking any action on it, but having said that, I would be totally fine with a pull request that added the ability to *optionally* cache the file listing across runs (I just don't think it would wind up being sufficiently faster than the "watchman" scanner to justify actually using it, given that Watchman can give up-to-date results at such a low cost).
