### ISSUE TITLE
Expected and actual ruby versions are the same, C extension cannot be loaded

### ISSUE THREAD

**Issue by snitko** [wincent/command-t#225]
Just recompiled vim (7.4.1689) with ruby support. Tried compiling command-t. Now upon trying to run `:CommandT` I get the weirdest error, which says:

    Command-T could not load the C extension
    Vim Ruby version: 2.3.0-p0
    Expected version: 2.3.0-p0

Any ideas what this might be?

**Comment by snitko** [comment]
Update: it looks like this problem only manifests itself in gvim, but not vim, which makes me think gvim uses some other version of vim. Not sure.

**Comment by snitko** [comment]
Closing the issue.
The solution: compile vim with GUI support

1. make sure dependencies are installed with `sudo apt-get build-dep vim`
2. enable gui when configuring with `./configure ... --enable-gui=gtk3`

**Comment by wincent** [comment]
Glad to hear you got it sorted out.

FWIW, I am working on making Command-T run outside of the Vim process (see #220), which should make this kind of issue go away, but it's a long-term project that will take a while to come to fruition.
