### ISSUE TITLE
<c-s> open selected file in a split new window doesn't work in cygwin's vim 

### ISSUE THREAD

**Issue by godhelpjun** [wincent/command-t#229]
As described above,when the file listing  has focused,pressing <c-s> does not work.just like I never pressed them and <c-t> sometimes work,sometimes not.sometimes need the key sequence <c-t><cr> .means that  sometimes I have to press a more <cr> to get the <c-t> to open the selected file in a new tab. I have tried with the lasted  cygwin and cygwin's vim.
any way,thanks for you incredible great job.It makes my life more easier!thanks a lot.

**Comment by wincent** [comment]
Are you running into [this](https://github.com/wincent/command-t/blob/354c429dad34f7d163663943c948f819588b53d3/doc/command-t.txt#L1235-L1253)?

**Comment by godhelpjun** [comment]
yes.something like that.the cygwin runs in mintty terminal.Is there any way to change this key binding to another?Like a <c-g> or anything others?thanks. love you.

**Comment by wincent** [comment]
> Is there any way to change this key binding to another?

Yes, use [g:CommandTAcceptSelectionSplitMap](https://github.com/wincent/command-t/blob/354c429dad34f7d163663943c948f819588b53d3/doc/command-t.txt#L1033-L1035).

I'm going to close this for now, but let me know if you have any further questions.

**Comment by godhelpjun** [comment]
thank you.I upgrade command-t to lasted version,and changing the key mapping as you told me.work just fine! love you so much!
