### ISSUE TITLE
ERROR: Unknown option --output-encoding with watchman

### ISSUE THREAD

**Issue by lencioni** [wincent/command-t#232]
I recently switched to the watchman file scanner, and the first time I was opening command-t in a session, I noticed

> ERROR: Unknown option --output-encoding

Running `watchman --output-encoding=bser get-sockname` on the command line gave me the same result.

After some poking around, it turned out that I had installed the watchman npm package globally instead of the homebrew formula. This gave me an entirely different program than what I wanted when running `watchman`. I fixed this by running:

```sh
npm uninstall -g watchamn
brew install watchman
```

I figured I would document this journey here to help out future travelers who might run into the same issue.

**Comment by RapsIn4** [comment]
👍  thanks
