### ISSUE TITLE
vundle install to a directoy which uses Title Case

### ISSUE THREAD

**Issue by mixmix** [wincent/command-t#233]
docs refer to this folder : 

```
~/.vim/bundle/command-t/ruby/command-t
```

https://github.com/wincent/command-t/blob/master/doc/command-t.txt#L313

But vundle installs to 

```
~/.vim/bundle/Command-T/ruby/command-t
```

Not a big deal, but consistency might be nice.

**Comment by mixmix** [comment]
clarify : I'm using vundle, I don't know if that's what's caused this capitalisation diff

**Comment by wincent** [comment]
Thanks for asking.

The repo on GitHub uses the lower-case name, which means it should be cloned with a lower-case name, and is why the docs use the lower-case name.

However, GitHub will allow you to clone with any capitalization: note that [https://github.com/wincent/CoMmAnD-t](https://github.com/wincent/CoMmAnD-t) does not 404. Also note that case-insensitive filesystems (ugh) like macOS's default HFS+ don't care either.

My guess is you specified "Command-T" in your Vundle config.

In a sane world all of this would be case-sensitive. Too many inconsistencies and surprises spring up as a result.

Going to close this for now. But let me know if you have anything further to add, or if this is actually causing anything to be broken for you (if so, we could add something to the troubleshooting section in the docs, or call out case-sensitivity in elsewhere in the installation instructions).

**Comment by mixmix** [comment]
well caught. that is the case with my vundle ... I wonder where I copied that from.

thanks for responding so clearly and thoroughly, I'll keep an eye out for people using inconsistent capitalization that you've described.

no breaks, was just wanting to make docs easier for people to use, as I've found myself rebuilding for different versions of ruby a bunch lately
