### ISSUE TITLE
Automatically switch to open tab

### ISSUE THREAD

**Issue by sstallion** [wincent/command-t#237]
When editing multiple files using tabs and buffers, I often make the mistake of opening a file that is already being edited in a different tab. It would be great if Command-T could switch to an open tab if the selected file/buffer/jump was already open.

**Comment by wincent** [comment]
Sorry I didn't see this earlier. You can configure Command-T to do this if you want.

You'll need to `:set switchbuf=usetab` ([like this](https://github.com/wincent/wincent/blob/c8a9dc074b81b77830efd245e06a5dbca311ea50/roles/dotfiles/files/.vim/plugin/settings.vim#L123)) and then you'll want something [like this](https://github.com/wincent/wincent/blob/c8a9dc074b81b77830efd245e06a5dbca311ea50/roles/dotfiles/files/.vim/after/plugin/command-t.vim#L35-L76) to actually use `:sbuffer` to do the opening for you:

```
function! s:BufHidden(buffer)
  let bufno = bufnr(a:buffer)
  let listed_buffers = ''

  redir => listed_buffers
  silent ls
  redir END

  for line in split(listed_buffers, "\n")
    let components = split(line)
    if components[0] == bufno
      return match(components[1], 'h') != -1
    endif
  endfor
  return 0
endfunction

function! s:GotoOrOpen(command_and_args)
  let l:command_and_args = split(a:command_and_args, '\v^\w+ \zs')
  let l:command = l:command_and_args[0]
  let l:file = l:command_and_args[1]

  " bufwinnr() doesn't see windows in other tabs, meaning we open them again
  " instead of switching to the other tab; but bufexists() sees hidden
  " buffers, and if we try to open one of those, we get an unwanted split.
  if bufwinnr(l:file) != -1 || (bufexists(l:file) && !s:BufHidden(l:file))
    execute 'sbuffer ' . l:file
  else
    execute l:command . l:file
  endif
endfunction

command! -nargs=+ GotoOrOpen call s:GotoOrOpen(<q-args>)

let g:CommandTAcceptSelectionCommand = 'GotoOrOpen e'
let g:CommandTAcceptSelectionTabCommand = 'GotoOrOpen tabe'
let g:CommandTAcceptSelectionSplitCommand = 'GotoOrOpen sp'
let g:CommandTAcceptSelectionVSplitCommand = 'GotoOrOpen vs'
```

This same info appears [in the docs](https://github.com/wincent/command-t/blob/354c429dad34f7d163663943c948f819588b53d3/doc/command-t.txt#L953-L973), so I am going to close this. Let me know if you have any other questions or comments.

**Comment by sstallion** [comment]
Thanks for the response - sorry for not taking a closer look!

**Comment by wincent** [comment]
No need to be sorry. I should probably bite the bullet in the next "major release" and make this the default behavior.
