### ISSUE TITLE
Huge repo size

### ISSUE THREAD

**Issue by RubenVerborgh** [wincent/command-t#239]
The size of this repo is huge because of `data/benchmark.yml`, which makes cloning this repo (for instance, as part of a default configuration) quite slow. Is it an option to move benchmark data outside of this repo?

**Comment by wincent** [comment]
Thanks for bringing this up, but it seems like a bit of a non-problem to me:

```
$ time git clone https://github.com/wincent/command-t.git
Cloning into 'command-t'...
remote: Counting objects: 6048, done.
remote: Total 6048 (delta 0), reused 0 (delta 0), pack-reused 6047
Receiving objects: 100% (6048/6048), 13.02 MiB | 3.16 MiB/s, done.
Resolving deltas: 100% (3121/3121), done.
Checking connectivity... done.
git clone https://github.com/wincent/command-t.git  1.24s user 0.53s system 32% cpu 5.407 total
```

That was 5.4s for a full clone on a shitty wifi connection. How often are you cloning, that you would consider it to be a bottleneck?

Given that Command-T's primary use case is working inside massive repositories (of a million files, or more), it seems likely that most of its users aren't going to be short of either CPU, disk, or network resources.

Also, note that although the file is 46M in size, Git packs are gzip compressed, which at the default compression ration comes down to about 3.7M. The file itself has changed few times in the repo history, and even then, Git's delta compression should make light work of it. Overall a full clone of the entire history of the repo downloads about 13M of object data.

If I delete this and move it into a submodule, you'll still be downloading it on every clone, unless you remember to pass the `--depth` option to `git-clone`, which I don't really think is worth it, for the reasons above.

**Comment by RubenVerborgh** [comment]
Should have been more complete; speed was not the only concern. Let me tell the full story.

I was initializing a couple of Linux machines by setting up my dotfiles. To my surprise, this quickly used a lot of my allotted shared disk space. Turns out that my dotfiles folder was 78MB on each machine (so with 10 machines and some rounding, that's 1GB of dotfiles). Turns out that 62MB per dotfile installation was due to command-t, 47MB of which is due to benchmark.yml. So, rounding again, that's 500MB of benchmark.yml on 10 machines.

Given that command-t is a popular plugin, and probably included in many dotfiles, this leads to tens of gigabytes of wasted disk space on Linux machines around the world 😉 

And yes, my Vim plugin system ([vim-plug](https://github.com/junegunn/vim-plug) does shallow clones by default, so without `benchmark.yml`, that's 3.7MB of bandwidth savings and 50MB of disk space for each command-t install worldwide. So I would say, maybe still significant after all!

**Comment by RubenVerborgh** [comment]
Here's [circumstantial evidence regarding wasted disk space globally](https://www.google.com/search?q=site:https:%2F%2Fgithub.com+%22dotfiles%22+%22vimrc%22+%22command-t%22) :wink:
