### ISSUE TITLE
Vim crashes after executing any :CommandT* command, installed from Macports

### ISSUE THREAD

**Issue by AlexAkhremenko** [wincent/command-t#240]
Installed port: vim @7.4.2196_0+big+python27+ruby20
ruby version: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
ruby version from vim: 2.0.0-p648

After executing any :CommandT* command vim is crashing.

**Comment by wincent** [comment]
Probably a miscompilation. Go back to the folder where you built Command-T (ie. the one containing the `extconf.rb`) and run:

```
make clean
ruby extconf.rb
make
```

**Comment by AlexAkhremenko** [comment]
many times. Without success

**Comment by AlexAkhremenko** [comment]
Does someone else have such behaviour?

**Comment by AlexAkhremenko** [comment]
Problem was solved. vim @7.4.2196_0+big+python27+ruby20 installs ruby2.0 dependency in system in addition with system ruby. I should use 'ruby2.0 extconf.rb' command.

**Comment by wincent** [comment]
Glad you got it sorted out. Thanks for sharing the solution.
