### ISSUE TITLE
vim ruby version === expected version and still can't load C extension

### ISSUE THREAD

**Issue by josh-m-sharpe** [wincent/command-t#247]
From within vim:
:ruby puts "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"
2.3.1-p112

Installation:

~  cd ~/.vim/bundle/command-t/ruby/command-t/

~/.vim/bundle/command-t/ruby/command-t (master) source ~/.rvm/scripts/rvm
~/.vim/bundle/command-t/ruby/command-t (master) rvm use 2.3.1
~/.vim/bundle/command-t/ruby/command-t (master) ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

~/.vim/bundle/command-t/ruby/command-t (master) ruby extconf.rb
checking for float.h... yes
checking for ruby.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for fcntl.h... yes
checking for stdint.h... yes
checking for sys/errno.h... yes
checking for sys/socket.h... yes
checking for ruby/st.h... yes
checking for st.h... yes
checking for pthread_create() in -lpthread... yes
creating Makefile

~/.vim/bundle/command-t/ruby/command-t (master) make
compiling match.c
compiling watchman.c
compiling matcher.c
compiling ext.c
compiling heap.c
linking shared-object ext.so

~/.vim/bundle/command-t/ruby/command-t (master) vim

command-t.vim could not load the C extension
Please see INSTALLATION and TROUBLE-SHOOTING in the help
Vim Ruby version: 2.3.1-p112
Expected version: 2.3.1-p112
For more information type:    :help command-t

**Comment by wincent** [comment]
The error message there is probably a bit misleading and should be changed. It makes it look like the extension failed to load *because* of a version number mismatch even though the numbers are the same, which is obviously nonsensical. What's actually happening here is that the version numbers get logged *any* time there is a failure to load, regardless of the cause.

How did you install Vim? And what is the output of `vim --version`?

**Comment by josh-m-sharpe** [comment]
I installed it the same way I've installed it on ubuntu for years:

apt-get install vim-nox (which is the package that has +ruby)

vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 10:50:38)
Included patches: 1-1689
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     +tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
-clientserver    +iconv           +packages        -toolbar
-clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      +lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      -mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm

**Comment by josh-m-sharpe** [comment]
Running on digital ocean: Ubuntu 16.04.1 LTS

**Comment by wincent** [comment]
Can you try compiling with the system Ruby instead of the RVM-managed one? (seeing as that is the one you `apt-get` installed one is linked against). Even though the version numbers match, there may be a discrepancy in the build flags that could cause the crash. Remember to do a `make clean` and re-run `ruby extconf.rb` when you try this.

**Comment by josh-m-sharpe** [comment]
That did it.  I also needed 'apt-get install ruby-devel'

Thanks!
