### ISSUE TITLE
C-w C-r to insert word currently under cursor

### ISSUE THREAD

**Issue by wincent** [wincent/command-t#259]
From a chat thread:

> pressing ctrl-r + ctrl-w to insert the last cursor word on the search
>
> that helps when i have my cursor on a superclass and want to open that file

**Comment by mitermayer** [comment]
awesome looking forward to it :)

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
