### ISSUE TITLE
Installation ruby issue

### ISSUE THREAD

**Issue by pdoak** [wincent/command-t#265]
I can see that a number of people have experienced similar problems and I have tried to work through the suggestions to resolve the issue but I still can't seem to get it working. I have Vim 8 linked against 2.4.0-p0 which I think is the system ruby version. Whereas command-t is using 2.3.1-p112. 

I am using rbenv and have tried setting the rbenv to system and to 2.4.0 before running ruby extconf.rb && make but command-t still is compiled with 2.3.1. 

I have also tried brew uninstall vim and brew install vim but it still does not work. I am probably making a silly mistake somewhere but I can't seem to get this working. Please could you help me resolve the problem.

Many Thanks

Paul

**Comment by wincent** [comment]
Sounds like you are on the right track. Did you `make clean` before rebuilding Command-T with the right version of Ruby?

**Comment by pdoak** [comment]
Thanks for responding so quickly.

I solved it. I had symlinked the .vim folder to another location and was running make on the wrong folder structure. Now I have changed the symlink, it all works. Just need to get clipper working and I will be set!!

**Comment by wincent** [comment]
Glad to hear you got it sorted out!
