### ISSUE TITLE
Command-T not caching at all

### ISSUE THREAD

**Issue by Jaco-Pretorius** [wincent/command-t#267]
I've recently started running into this issue where Command-T doesn't cache the results at all.  This means the first time I open it it takes about 6/7 seconds to build the cache, and every subsequent time it takes the same amount of time.

I've looked through all the issues and searched online but I can't find any documentation around this problem.  I'm sure it must be something to do with my setup or configuration but I'm completely stumped.

Some information re: my setup:
 - Installed via vundle
- `:ruby puts "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"` gives `2.0.0-p648`
- I'm using MacVim 8.0 (124)

**Comment by wincent** [comment]
Any chance you have `'autochdir'` turned on? That would break the cache, especially if you leave `g:CommandTMaxCachedDirectories` at the default of 1.

Closing this because it is old but feel to comment if this is still an issue for you and I will re-open it.
