### ISSUE TITLE
Ctrl-Backspace in gnome-terminal moves cursor left instead of deleting word

### ISSUE THREAD

**Issue by mgedmin** [wincent/command-t#272]
## Steps to reproduce

1. Hit `<Leader>t` to trigger command-t
2. Type some text
3. Hit Ctrl-Backspace

## What I expect
- the last path segment gets deleted
- or, at the very least (assuming the terminal can't distinguish Backspace from Ctrl-Backspace) the last character is erased

## What actually happens
- the cursor moves left

## Additional details
- `<C-V>` `<C-Backspace>` in insert mode shows that gnome-terminal sends a ^H on Ctrl-Backspace.  The regular backspace sends a ^?.  Vim's `&t_kb` is ^?.

**Comment by mgedmin** [comment]
I'm curious: why is `C-h` bound to moving left by default?  I would understand it being mapped to backspace (since I think some terminals still emit ^H for backspace), but I don't think I've ever seen it bound to moving left.

**Comment by wincent** [comment]
`C-h`, `C-j`, `C-k` and `C-l` and mapped to movement in directions corresponding to Vim's own `h`/`j`/`k`/`l` keys.

**Comment by mgedmin** [comment]
Let's close this as invalid then.  I'm happy enough that I can tweak this with settings for my own convenience.
