### ISSUE TITLE
Cannot load C extensions with ruby 2.3.1

### ISSUE THREAD

**Issue by xianny** [wincent/command-t#275]
I get this error after building:

```
command-t.vim could not load the C extension
Please see INSTALLATION and TROUBLE-SHOOTING in the help
Vim Ruby version: 2.3.1-p112
Expected version: 2.3.1-p112
```

I first built command-t with ruby 2.3, got the usual error, then used `rvm` to switch to 2.3.1. Then ran `make clean && ruby extconf.rb && make`. Restarted vim and got this error.

My system:
```
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
$ which ruby
~/.rvm/rubies/ruby-2.3.1/bin/ruby
```
In Vim, `:ruby puts "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"` gives `2.3.1-p112 `

**Comment by xianny** [comment]
I just found [this old issue](https://github.com/wincent/command-t/issues/214) and recompiled command-t with system ruby. Now it works!

Feel free to delete this thread if you prefer.

**Comment by wincent** [comment]
Glad to hear you got it sorted out.
