### ISSUE TITLE
Make new finders take optional args to preseed them with content

### ISSUE THREAD

**Issue by wincent** [wincent/command-t#280]
Not sure if I would use this myself but others might want to make mappings for it.

**Comment by GriffinHeart** [comment]
I would love to preseed command-t finders with the current search register `/`, haven't found a way to do this

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
