### ISSUE TITLE
Make use of memoization matrix to reconstruct matching characters for highlighting purposes

### ISSUE THREAD

**Issue by wincent** [wincent/command-t#286]

**Comment by Aster89** [comment]
To avoid duplicating the issues. Is the title referring to the behavior below?
[![asciicast](https://asciinema.org/a/29rEOFNjmkL5FXS7r62r8hNQd.svg)](https://asciinema.org/a/29rEOFNjmkL5FXS7r62r8hNQd)

**Comment by wincent** [comment]
Yes, that's right @Aster89. The way Command-T works (unless configured otherwise) is to recursively try all the possible ways of scoring a given match, and to use the highest-scoring one for each path (for the purposes of ranking the matches relative to each other). This is done using the "memoization matrix" mentioned in the title. So, if you search for "abc" and one of the paths is "apple/banana/abc", Command-T will calculate the scores for all of these ways of matching:

```
apple/banana/abc
^     ^        ^
apple/banana/abc
^             ^^
apple/banana/abc
       ^      ^^
apple/banana/abc
         ^    ^^
apple/banana/abc
           ^  ^^
apple/banana/abc
             ^^^
```

Now, the memoization matrix "knows" which match positions produced the highest score, but it is an implementation detail of the scoring algorithm; by the time the Vim-side code comes along to do the highlighting, it doesn't have access to the matrix or know anything about it — so it just does the dumbest/fastest thing and highlights the first possible match for each character, using a simple greedy algorithm, which is what you're seeing in your recording.

**Comment by Aster89** [comment]
Thanks for the detailed explanation. I guess the code that would need to be changed in order for it to expose these details (well, since you do hightlight stuff, I guess it qualifies them as non-implementation details anymore, no?) is a Ruby code, right?

**Comment by wincent** [comment]
Right, [the Ruby code which is highlighting the string is here](https://github.com/wincent/command-t/blob/6a00a2cabfb5ee3f49ff556ceea56892825c0397/ruby/command-t/lib/command-t/match_window.rb#L402-L424). The  memoization is happening in C-land ([see `memo` in this file](https://github.com/wincent/command-t/blob/6a00a2cabfb5ee3f49ff556ceea56892825c0397/ruby/command-t/ext/command-t/match.c#L23), which is what I am calling an "implementation detail").

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
