### ISSUE TITLE
command-t buffer remains open with vim-startify

### ISSUE THREAD

**Issue by swalladge** [wincent/command-t#288]
Steps to reproduce:

1. open vim when [vim-startify](https://github.com/mhinz/vim-startify) is enabled
2. start command-t
3. open a file with command-t, or press esc to cancel
4. command-t buffer remains open, and crashes with an "invalid buffer id" error when trying to interact with it afterwards

This only affects it when first opening vim - if :Startify is run later during a session and command-t is then called, there are no problems.
I suspect it's something to do with vim-startify setting a combination of buffer options so it isn't treated as a normal file, and command-t is making some assumptions that causes it to lose its buffer id or something.

**Comment by wincent** [comment]
I wouldn't be surprised if vim-startify is doing something funky with autocommands (suppressing them in some way, or perhaps double/early triggering them).

Not a startify user myself, but I will have a look into it at some point. Let me know if you discover anything else in the meantime, and thanks for the report.

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
