### ISSUE TITLE
error following update

### ISSUE THREAD

**Issue by servicelevel** [wincent/command-t#294]
why hello there.
after a recent update `command-t` no longer functions, and i am receiving the following error:

```
command-t.vim could not load the C extension.
Please see INSTALLATION and TROUBLE-SHOOTING in the help.
Vim Ruby version: 2.0.0-p648
Expected version: [unknown]-p[unknown]
For more information type:    :help command-t
```

i am not sure why the expected version is marked unknown. the output of `ruby --version` matches the vim version listed.
`rbenv` is used for ruby version management, and in case it matters, i have set the global version accordingly and ran `rbenv rehash` just in case.

any help would be appreciated.
oh, and no be clear. everything was functioning perfectly fine before `:PlugUpdate` the other day, but i am not sure where the last 'version' i ran was at. i suspect it to have been around `5c86458`

**Comment by servicelevel** [comment]
100% my bad - looks like `extconf.rb` had moved to `ruby/command-t/ext/command-t` where previously it was `ruby/command-t`.

my apologies. closing

**Comment by wincent** [comment]
Sorry you ran into trouble. I knew that moving things might cause issues, so I held off on doing it for a long while; but in the end I had to bite the bullet: unfortunately with everybody using a plug-in manager to track the `HEAD` of the `master` branch, rolling out any kind of risky or breaking change is fraught with peril... And while there are release notes, nobody is really going to see or read them... In any case, I don't think these files will be moving again in the future, so hopefully this specific pitfall won't reoccur ever again.

**Comment by servicelevel** [comment]
thanks Greg - i think the 'fault' is with me, or the various plugin managers maybe for not making error messages or a changelog visible.

ultimately tho - i should have completed basic troubleshooting steps before opening an issue, so its my bad.
thanks for the support anyhow, and keep up the great work!!!
