### ISSUE TITLE
can not compile on win7, vim8.0

### ISSUE THREAD

**Issue by liqingshuo** [wincent/command-t#297]
i got the following error when i run ruby extconf.rb. i had installed ruby and devkit.
Any advice will be help.
$ ruby extconf.rb
checking for float.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=D:/Ruby22/bin/$(RUBY_BASE_NAME)
D:/Ruby22/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from D:/Ruby22/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
        from D:/Ruby22/lib/ruby/2.2.0/mkmf.rb:1113:in `block in find_header'
        from D:/Ruby22/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from D:/Ruby22/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from D:/Ruby22/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from D:/Ruby22/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from D:/Ruby22/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from D:/Ruby22/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from D:/Ruby22/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from D:/Ruby22/lib/ruby/2.2.0/mkmf.rb:1112:in `find_header'
        from extconf.rb:18:in `header'
        from extconf.rb:25:in `<main>'

**Comment by wincent** [comment]
Sorry, but I haven't even tried installing Command-T on Windows for about 5 years now and I have no machines to test on, so you should probably ask this somewhere where you'll get more visibility from people who us Windows. (Maybe a Stack Exchange site? Not sure which one would be best.)

As there is nothing actionable here for me, I am going to close this. But if you find out any useful installation tips that would go well in the docs, please let me know so I can add them.
