### ISSUE TITLE
Error message issue

### ISSUE THREAD

**Issue by alimsky** [wincent/command-t#299]
Hey guys,

I spent some time trying to figure out what was wrong with my setup after compiling make file on one of my work stations with Linux (and I am not a Linux user)

```ruby extconf.rb
checking for float.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/ruby2.0/bin/ruby
/opt/ruby2.0/lib/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/ruby2.0/lib/2.0.0/mkmf.rb:565:in `try_cpp'
	from /opt/ruby2.0/lib/2.0.0/mkmf.rb:1091:in `block in find_header'
	from /opt/ruby2.0/lib/2.0.0/mkmf.rb:889:in `block in checking_for'
	from /opt/ruby2.0/lib/2.0.0/mkmf.rb:340:in `block (2 levels) in postpone'
	from /opt/ruby2.0/lib/2.0.0/mkmf.rb:310:in `open'
	from /opt/ruby2.0/lib/2.0.0/mkmf.rb:340:in `block in postpone'
	from /opt/ruby2.0/lib/2.0.0/mkmf.rb:310:in `open'
	from /opt/ruby2.0/lib/2.0.0/mkmf.rb:336:in `postpone'
	from /opt/ruby2.0/lib/2.0.0/mkmf.rb:888:in `checking_for'
	from /opt/ruby2.0/lib/2.0.0/mkmf.rb:1090:in `find_header'
	from extconf.rb:18:in `header'
	from extconf.rb:25:in `<main>'
```

The mkmf.log file didn't contain any additional information. Just the command and the test program:
```
"gcc -o conftest -I/opt/ruby2.0/include/ruby/ruby-2.0.0/x86_64-linux -I/opt/ruby2.0/include/ruby/ruby-2.0.0/ruby/backward -I/opt/ruby2.0/include/ruby/ruby-2.0.0 -I.    -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -mtune=generic -Wall -fno-strict-aliasing -fPIC conftest.c  -L. -L/opt/ruby2.0/lib64 -Wl,-R/opt/ruby2.0/lib64 -L. -fstack-protector -rdynamic -Wl,-export-dynamic  -m64   -Wl,-R -Wl,/opt/ruby2.0/lib64 -L/opt/ruby2.0/lib64 -lruby  -lpthread -lrt -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

The issue was that my version of Linux didn't have C compiler installed at all. So I had to install gcc, in my case:
```yum install gcc``` 
and it was a solution. 

I understand that it is probably an edge case, but it could be useful for people with a certain setup to have an additional paragraph in command-t-requirements. Now it assumes that Linux has gcc by default, which is not always the case.

**Comment by wincent** [comment]
Thanks for bringing this up. Feel free to submit a PR to improve the documentation.

Unfortunately, people tend not to read that (it is very long, so even if the info is in there it may not be obvious where to find it), but that is the most obvious place for us to try and improve this. (Command-T isn't the one printing the error message, rather `mkmf` in the Ruby standard library is, so we can't easily change that.)

Closing this, but like I said above, PR would be welcome. Thanks once again.
