### ISSUE TITLE
Arrow keys mapping to <ESC>OA

### ISSUE THREAD

**Issue by codybuell** [wincent/command-t#300]
After opening command-t trying to navigate up and down the file listing with the arrow keys results in <ESC>OA being passed in, closing command-t opening a new line above and typing A or D.  Same goes for left and right arrow keys, outputting B or C.  `set nocompatible` is set and the arrow keys function as expected outside of command-t.

Running the latest pull of command-t from master as of today, with Vim 8.0 patches 1-823, on iTerm2 build 3.0.15.

**Comment by wincent** [comment]
You probably want something like this, I imagine:

```
if &term =~# 'screen' || &term =~# 'tmux' || &term =~# 'xterm'
  let g:CommandTSelectNextMap = ['<C-n>', '<C-j>', '<Down>', '<ESC>OB']
  let g:CommandTSelectPrevMap = ['<C-p>', '<C-k>', '<Up>', '<ESC>OA']
 endif
```

Closing, but please comment if the above doesn't solve the problem for you.

**Comment by wincent** [comment]
(And same deal for `g:CommandTCursorRightMap` and `g:CommandTCursorLeftMap`.)
