### ISSUE TITLE
Ctrl-W refuses to delete anything past punctuation

### ISSUE THREAD

**Issue by salty-horse** [wincent/command-t#301]
Using latest git.

In the Command-T search prompt, pressing Ctrl-W to clear the previous word will stop on punctuation such as "," or ".", and will not delete it.

This is unexpected, and doesn't match the default  behavior of Ctrl-W in vim, bash, etc. It should delete everything up to the previous word boundary.

(While "word boundary" is implementation-defined, there's no question that repeated presses of Ctrl-W should delete SOMETHING if there's still text to delete)

**Comment by wincent** [comment]
Totally agreed. Thanks for reporting this.
