### ISSUE TITLE
wildignore doesn't work anymore

### ISSUE THREAD

**Issue by RubenVerborgh** [wincent/command-t#302]
I've been using [my `wildignore` settings](https://github.com/RubenVerborgh/dotfiles/commit/f3b83348498b9185235383db6e5b471af38477ff) for a long time, but after upgrading some time ago, I noticed that these settings are not respected anymore.

Concretely, I'm asking to ignore `node_modules/`, and Vim respects it, but command-t recursively lists all files inside of `node_modules`. This used to work fine.

**Comment by RubenVerborgh** [comment]
I've tried `git bisect`, but it brings me back to the parentless commit fca7e89e6afbf6df82ccf66b6bfaecc6f4720617.

**Comment by RubenVerborgh** [comment]
With `git bisect`, I found that breakage happened in 4b94a60a32cf65550ebb410da2e50d225e4f4e2f.

**Comment by wincent** [comment]
I think you probably want:

```
+set wildignore+=*/node_modules/*     " Don't search inside Node.js modules
 +set wildignore+=*/bower_components/* " Don't search inside bower modules
```

**Comment by wincent** [comment]
Note that if you don't want to change `'wildignore'` itself, you can instead use `g:CommandTWildIgnore` ([docs](https://github.com/wincent/command-t/blob/85949ce7a70a26abf6f9d355e38d1473facba022/doc/command-t.txt#L921)).

Further reading on what patterns should look like can be found [here](https://github.com/wincent/command-t/blob/85949ce7a70a26abf6f9d355e38d1473facba022/doc/command-t.txt#L1102).

**Comment by RubenVerborgh** [comment]
Thanks, no idea where I got the `**`. Maybe worth mentioning that command-t's interpretation is different of Vim's.

**Comment by wincent** [comment]
I'm not sure it is different. AFAIK `**` is not a Vim thing.

**Comment by RubenVerborgh** [comment]
It's not a thing in the sense that it doesn't have special meaning (as I found out, thanks to your comment). However, Vim interprets `**` as `*`, and so did 4.0 of Command-T, but not 5.0. My mistake for writing `**` of course, but I was confused that Vim took it but Command-T didn't.
