### ISSUE TITLE
Command-t only lists 15 entries

### ISSUE THREAD

**Issue by colmheaney** [wincent/command-t#303]
I'm facing a problem where Command-t only lists a maximum of 15 entries no matter how many files are in the directory.

I'm using the system Vim (7.4) on Sierra and have compiled command-t using the system ruby 2.0.0

```
:ruby puts "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"
2.0.0-p648
```

I did:
```
> cd ~/.vim/bundle/command-t/ruby/command-t
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
> make
compiling ext.c
compiling match.c
compiling matcher.c
linking shared-object ext.bundle
```

I've tried setting g:CommandTMaxFiles to a large number but this has no effect and besides all of the directories I've tested have been less than the 100,000 files default value.

**Comment by wincent** [comment]
Sounds like you don't like the default value of `g:CommandTMaxHeight` ([docs](https://github.com/wincent/command-t/blob/85949ce7a70a26abf6f9d355e38d1473facba022/doc/command-t.txt#L749)).

You can either set it to `0` (to use all available space) or some other number greater than 15. Or, just start typing letters from the path & filename that you're searching for, and it will soon appear in the top 15 results.

**Comment by colmheaney** [comment]
Ah, my apologies, I knew I must have been doing something stupid! Thanks for the quick response
