### ISSUE TITLE
Watchman.c return error during installation

### ISSUE THREAD

**Issue by suborx** [wincent/command-t#308]
Setup: Ubuntu 16.04, Ruby 2.4.1, RVM, Vim 8 (with ruby support)
Issue: During compilation I get this error. 

`compiling watchman.c`
`watchman.c: In function ‘watchman_raise_system_call_error’:`
`watchman.c:546:6: warning: function might be candidate for attribute ‘noreturn’ [-Wsuggest-attribute=noreturn]`
` void watchman_raise_system_call_error(int number) {`
`      ^`
`watchman.c: At top level:`
`cc1: warning: unrecognized command line option ‘-Wno-self-assign’`
`cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’`
`cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’`
`cc1: warning: unrecognized command line option ‘-Wno-tautological-compare’`
`linking shared-object ext.so`

I also installed watchman, but it didn't solve the probelm.

Can you please help?

**Comment by wincent** [comment]
Is I gather it worked but with warnings?

**Comment by suborx** [comment]
Thank you for reply. Problem is solved, suddenly it start working when I install and run watchman.

**Comment by wincent** [comment]
Great.
