### ISSUE TITLE
<C-t> opens a horizontal split instead of a new tab

### ISSUE THREAD

**Issue by Bladtman242** [wincent/command-t#311]
\<C-t\> opens a horizontal split instead of a new tab.
It doesn't happen every time, but I haven't been able to discern a pattern.

**Comment by adrianhelvik** [comment]
2nd this. To clarify. It opens a new split pane instead of utilising the current buffer. The current buffer does not have unsaved content. It is seemingly random.

**Comment by wincent** [comment]
What's the value of `:set switchbuf?`

**Comment by adrianhelvik** [comment]
usetab

**Comment by adrianhelvik** [comment]
I'm able to reproduce this easily. After pressing ‹leader›-t and selecting a random file a few times (I tested it now and it first took 9 times, then 6 times), the tab splits. Subsequent ‹leader›-t create new splits. For me the split is however vertical and not horizontal.

**Comment by adrianhelvik** [comment]
The same thing happens on my colleagues computer.

**Comment by Bladtman242** [comment]
The value of switchbuf is usetab.

**Comment by wincent** [comment]
I'm not able to reproduce this, but I'm looking at #315 and will see if that can be merged without introducing any regressions.

**Comment by wincent** [comment]
#315 is merged into `master` now, so let's close this. If it isn't resolved for you, please comment and I can re-open it.

**Comment by a-d-v-e-n-t-u-r-o-u-s** [comment]
Hi, 
I had the same problem with version from 5.0.2 tag with following SHA-1 sum: 
1c797d0aa835743a9a8addd7b2c70d7f7ff9ff1a

After rebasing on current master, problem seems to dissapear
7147ba92c9c1eef8269fd47d47ba636ce7f365a6
