### ISSUE TITLE
[CommandTMRU]  File selection always opens in a new split buffer

### ISSUE THREAD

**Issue by nirajgup** [wincent/command-t#314]
On CommandTMRU window, 

1. Selecting a file most of the time opens in a horizontal split window instead of opening in the same buffer
2. Shortcuts like C-v, C-<cr>, C-t doesn't work as expected

**Comment by aptiko** [comment]
I have the same problem since the last time I updated.

**Comment by nirajgup** [comment]
FYI, this issue doesn't seem to exist on [5.0.1](https://github.com/wincent/command-t/releases/tag/5.0.1)

**Comment by wincent** [comment]
Thanks for reporting back @nirajgup. I'll close this. If anybody else is still seeing this or an issue like it after updating to the latest release, please create a new issue and we can discuss it there.

**Comment by nirajgup** [comment]
@wincent Sorry, my bad. I meant this issue didn't exist on 5.0.1 but exists on the latest version. 
So this is a new issue. Can you reopen this ticket?

**Comment by wincent** [comment]
I merged #315, so please let me know if this is still an issue on the master branch. At least, I couldn't repro it...

**Comment by nirajgup** [comment]
I am not able to see this issue anymore after updating. The changes seems to have fixed this issue.
