### ISSUE TITLE
Dismiss file listing using <Esc> in iTerm2

### ISSUE THREAD

**Issue by mjackson** [wincent/command-t#322]
[The docs say](https://github.com/wincent/command-t/blob/7147ba92c9c1eef8269fd47d47ba636ce7f365a6/doc/command-t.txt#L520-L522) that I should be able to use `<Esc>` to dismiss the file listing, but I can't seem to get this to work in iTerm2. Has anyone else been able to do this?

**Comment by wincent** [comment]
You probably want something like this (specifically, line 6):

https://github.com/wincent/wincent/blob/e0daaa08d2c7d4e06c596cfaed9983e650ea3ad0/roles/dotfiles/files/.vim/after/plugin/command-t.vim#L5-L9

**Comment by mjackson** [comment]
Ah, yep! That did it! Thanks @wincent :D
