### ISSUE TITLE
CommandTSearch documentation may be unclear

### ISSUE THREAD

**Issue by dylan-chong** [wincent/command-t#326]
I expect that CommandTSearch brings up the list of search terms typed into CommandT. However, it brings up a list of commands (e.g. `:w`)

---

EDIT: The above text is wrong . See my  comment below https://github.com/wincent/command-t/issues/326#issuecomment-367552119

**Comment by wincent** [comment]
What version are you using? This doesn't repro for me.

**Comment by dylan-chong** [comment]
happened on commit `7147ba9`

**Comment by wincent** [comment]
Might be worth trying the "next" branch. That's the one I use. Not at my computer to test master right now.

**Comment by dylan-chong** [comment]
btw on mac os 10.13.2, replicated on  neovim  0.2.2

also interestingly:

```
> git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ruby/command-t/Makefile
        ruby/command-t/ext.bundle
        ruby/command-t/ext.o
        ruby/command-t/heap.o
        ruby/command-t/match.o
        ruby/command-t/matcher.o
        ruby/command-t/metadata.rb
        ruby/command-t/mkmf.log
        ruby/command-t/watchman.o
```

and same issue on `next` branch

**Comment by wincent** [comment]
You should probably delete the untracked files.

**Comment by dylan-chong** [comment]
clearing that then running

```
    cd ~/.vim/bundle/command-t/ruby/command-t/ext/command-t
  ruby extconf.rb
  make
```

as per readme yeilds same result

**Comment by wincent** [comment]
Can you provide a more detailed repro? Otherwise there is nothing to do here (I already inspected the code and can't see any obvious defects.)

**Comment by dylan-chong** [comment]
0. Install CommandT with Vundle and close vim
0.1. Run 

```
  cd ~/.vim/bundle/command-t/ruby/command-t/ext/command-t
  ruby extconf.rb
  make
```

1. Open nvim
2. Type `:CommandTSearch`

I'll try and replicate and a minimal doctor image if you cannot replicate it

**Comment by wincent** [comment]
Already told you it doesn't repro.

**Comment by wincent** [comment]
Also, I asked you if it repros for you on the "next" branch, which is ahead of "master".

**Comment by dylan-chong** [comment]
I'm having some problems with Docker. Will try later I have more time

**Comment by dylan-chong** [comment]
I had a loook at the code and perhaps the documentation is a little misleanding. A looks like  `CommandTSearch` looks to the vim `/` history. The documentation for this function is  

` Brings up the Command-T search window. This works
                  exactly like the standard file window, except that it shows
                  the history of previously used searches.
`

I had interpreted the word `searches` as text used to filter files in `:CommandT`.  Perhaps we could make it clear in the documentation that the search function lists searches?

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
