### ISSUE TITLE
Add a way to quickly reuse a recent search term

### ISSUE THREAD

**Issue by dylan-chong** [wincent/command-t#328]
I might want to open files `abc.html`, `abc.scss`, `abc.js`. I will start by doing `:CommandT<CR>abc` and then selecting one of the files. 

I would like to be up to reopen commandt, reuse my previous search of `abc` and then select another file. Currently i would type in `abc` again, which gets tedious if the filename is quite long (and there are many files with similar names)

**Comment by dylan-chong** [comment]
@wincent Would it be possible to add some keyboard shortcuts to navigate up and down the list of previously used search terms, similar to how vim command mode does it. Obviously we would have to use different key would shortcuts. e.g. `C-9` to go up the list and `C-0` to go down the list

**Comment by wincent** [comment]
Keyboard shortcuts for this make a lot of sense. I think there may be an existing issue for this; let me see if I can find it.

**Comment by wincent** [comment]
Found it (#153); let's merge this into that.
