### ISSUE TITLE
Command-t works but spews errors in console when changing ruby via RVM

### ISSUE THREAD

**Issue by lightcap** [wincent/command-t#330]
Everything seems to work just fine when I run MacVim with command-t after changing to ruby 2.5.0 via rvm.

But the second I try to use any other Ruby with rvm I get a flurry of errors about gem extensions not being built.

command-t was compiled against ruby-2.5.0, and the output from `:ruby puts "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}" ` is also `2.5.0-p0`.

Given that command-t and MacVim were linked to the proper Ruby version at compile time, I don't understand why changing Ruby versions with RVM would affect anything at all. 

Any insight here? Things seem to work, but the errors are 1) annoying and 2) concerning since I don't know what else it may be affecting.

It's also worth noting that this only seems to happen when running `mvim` from the command line. But, then I don't know where the output would go when running the app outside the command line.

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
