### ISSUE TITLE
[Discussion] Automatically run flush after a certain time out or some other solution

### ISSUE THREAD

**Issue by dylan-chong** [wincent/command-t#333]
There is the annoying problem of creating a new file and then trying to find it in command t and it not being there. I'm not really sure what to do about this...

**Comment by wincent** [comment]
We could probably merge this one into #238.

**Comment by dylan-chong** [comment]
Maybe, but will that solve the problem if we do not use watchmen?

**Comment by wincent** [comment]
Nope. You could always just get in the habit of hitting `C-f` to flush the listing if you can't find what you're looking for.

**Comment by dylan-chong** [comment]
Ah, i did not think of this! I guess this makes this issue much less important then
