### ISSUE TITLE
your instructions are wrong wincent

### ISSUE THREAD

**Issue by thefonso** [wincent/command-t#335]
This set of instructions you have posted 

```
Note: If you are an RVM or rbenv user, you must build CommandT using the same
version of Ruby that Vim itself is linked against. You can find out the
version that Vim is linked against by issuing following command inside Vim:

  :ruby puts "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"

Or, for very old versions of Ruby which don't define `RUBY_PATCHLEVEL`:

:ruby puts RUBY_VERSION

```
Yield this error....
```
﻿E370: Could not load library libruby.2.5.dylib
E266: Sorry, this command is disabled, the Ruby library could not be loaded.
```

PLEASE PROVIDE CORRECT INSTRUCTIONS. Since we have do this routine every 5 years or so. Thank you.

**Comment by wincent** [comment]
Instructions are correct, but don't necessarily cover every possible edge case. In this instance, sounds like your Vim install and/or system Ruby are busted, and this is unrelated to Command-T. To verify this, remove all trace of Command-T from your system, and see that even a command like `:ruby p 1` explodes spectacularly.

All the best fixing your system.
