### ISSUE TITLE
Hey guys some problems with my vim config

### ISSUE THREAD

**Issue by Niubi90hou** [wincent/command-t#336]
Warning: maximum file limit reached

Increase it by setting a higher value in $MYVIMRC; eg:
  let g:CommandTMaxFiles=200000
Or suppress this warning by setting:
  let g:CommandTSuppressMaxFilesWarning=1
For best performance, consider using a fast scanner; see:
  :help g:CommandTFileScanner

**Comment by wincent** [comment]
Seems like the message contains the information you're looking for. Feel free to comment again if you need additional help.
