### ISSUE TITLE
Doesn't work on Vim even after compiling

### ISSUE THREAD

**Issue by mbackermann** [wincent/command-t#337]
I'm trying to use it with Vim 8.1, which uses ruby 2.5.1.

I followed the installation instructions, ran ruby extconf.rb and got the following output
`checking for float.h... yes
checking for ruby.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for fcntl.h... yes
checking for stdint.h... yes
checking for sys/errno.h... yes
checking for sys/socket.h... yes
checking for ruby/st.h... yes
checking for st.h... yes
checking for pthread_create() in -lpthread... yes
creating Makefile`

then I ran make and got:

`compiling ext.c
compiling heap.c
compiling match.c
compiling matcher.c
compiling watchman.c
linking shared-object ext.bundle`

but when I try to access it inside vim, I got the following message

`command-t.vim could not load the C extension.
Please see INSTALLATION and TROUBLE-SHOOTING in the help.
Vim Ruby version: 2.5.1-p57
For more information type:    :help command-t`

My ruby version is 2.5.1. I also tried compiling it with ruby 2.5.0 and I got a different message, telling me that the Command-T version was wrong. But when I compile it with ruby 2.5.1 I got the message that it's not compiled at all.

**Comment by wincent** [comment]
What's the output of `ruby --version` and `vim --version` on the command line? What operating system and version are you on?

**Comment by wincent** [comment]
Nothing looks out of order there. Personally I'd try a cleaning (`make clean`) and rebuilding to see if the problem goes away. Failing that, I think I'd change [this line](https://github.com/wincent/command-t/blob/7147ba92c9c1eef8269fd47d47ba636ce7f365a6/autoload/commandt.vim#L231) to:

```
raise
```

to see whether I could see more detail about the exception that is probably being raised when you're trying to use Command-T. Even if you do that, there is a chance that the error text might get swallowed or overwritten when Vim updates the UI, so it might be necessary to log it to a file so you can actually see it.

**Comment by mbackermann** [comment]
Actually, I could solve using rvm use system. Probably was a problem with RVM. It's now working. Thanks a lot all the help.
