### ISSUE TITLE
Ability to define mapping to a user-defined action to be performed on selected match

### ISSUE THREAD

**Issue by joereddington** [wincent/command-t#340]
I love this plugin. 

I'd like to be able to use it to open a particular directory in the explore view. At the moment I'm finding a file in the target directory and doing ":Ex" but I feel like there is probably a better way. 

Bonus - I'm also interested in using CommandT to effectively as a launcher - I sometimes want to find a, say, pdf and open it without leaving vim - atm I'm opening it in vim and doing :!open "%" - but, again, I feel like that's a rubbish way (particularly with big files).

**Comment by wincent** [comment]
Good questions @joereddington. Command-T only cares about files, not directories, so I don't think it would ever provide a way of searching for directories; on the other hand adding a mapping that says "open the directory of this file" is within the realms of possibility. We'd just need to figure out how to make it adequately configurable; I imagine some people would want to use `:Explore', and others would want something else.

Likewise, for using it as a launcher, it is possible that we could set up a generic action mechanism whereby you could define a mapping that would execute some user-defined action for the selected file. That could be useful. And you could probably use this second feature to implement the first one. I'm going to retitle this to reflect what would be needed to make this happen.

However, having said all that, a tool like FZF which is usuable pretty much anywhere (including outside Vim and on the command-line) may be a better fit for these kinds of use cases.

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
