### ISSUE TITLE
MacOS Missing development tools

### ISSUE THREAD

**Issue by jahvix** [wincent/command-t#345]
I've followed the installation instructions, but running `ruby extconf.rb` yields the error:

```
Checking for float.h... /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:571:in `block in try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:524:in `with_werror'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:571:in `try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1144:in `block in find_header'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1143:in `find_header'
	from extconf.rb:18:in `header'
	from extconf.rb:25:in `<main>'
```

This is on MacOS Mojave 10.14.

I'm not sure how to install the additional development tools required. I've installed Ruby development dependencies `brew install ruby-dev` and additional development tools via `xcode-select --install`.

Any suggestions?

**Comment by bradwood** [comment]
You probably need to install XCode from MacOSX App Store.

**Comment by ecdemis123** [comment]
I am also having this same issue. Were you able to figure out a solution? 

I already have XCode installed.

**Comment by wincent** [comment]
You could try `xcode-select --install`, which supposedly installs the BSD development tools as well. I haven't updated to Mojave myself, so I am flying blind as far as troubleshooting goes.

**Comment by ecdemis123** [comment]
Thanks, I'll give that a try next. I'm upgrading Xcode right now to 10.1 so we'll see how it goes once I do that.

I've tried a couple of things from this thread but none of them have worked yet. https://github.com/wincent/command-t/issues/341

I'll update here when I figure out a solution.

**Comment by ecdemis123** [comment]
This is what I did to get it working https://github.com/wincent/command-t/issues/341#issuecomment-457359052

**Comment by wincent** [comment]
Closing based on success reported in #341.
