### ISSUE TITLE
avoiding jump to another tab from quickfix

### ISSUE THREAD

**Issue by shahar3000** [wincent/command-t#347]
hey,
I use a quickfix list on a currently open tab and when I choose an entry which its location is already opened in another tab, it jumps to the latter instead of opening the entry in the current tab
so this "feature" avoids from having two open tabs in the same path, although this is exactly what I want.

How can I disable this behavior?

**Comment by wincent** [comment]
Make sure you have 'switchbuf' set to something before loading Command-T.

See: https://github.com/wincent/command-t/blob/7147ba92c9c1eef8269fd47d47ba636ce7f365a6/plugin/command-t.vim#L11

Command-T will set it to "usetab", but only if the user hasn't already set it to something.

'switchbuf' docs here: http://vimdoc.sourceforge.net/htmldoc/options.html#%27switchbuf%27
