### ISSUE TITLE
E492: Not an editor command: CommandT

### ISSUE THREAD

**Issue by Qwertie-** [wincent/command-t#351]
I installed command-t via vim plug and ran make to build the plugin and then I opened vim and typed :CommandT and got the error

`E492: Not an editor command: CommandT`

Using vim 8.1.998 and fedora 29

**Comment by Qwertie-** [comment]
nvm, I forgot to add `call plug#end()` to my .vimrc file

**Comment by wincent** [comment]
Glad to hear you got it sorted.
