### ISSUE TITLE
fallback.rb not overwritten when executing `ruby extconf.rb`

### ISSUE THREAD

**Issue by julijavin** [wincent/command-t#370]
I was having issues running command-t, with errors indicating incompatible ruby versions between vim and ruby even though I only have one version of ruby installed. I noticed that the ~/.vim/bundle/command-t/ruby/command-t/lib/command-t/metadata/fallback.rb file contained:
`EXPECTED_RUBY_VERSION = '[unknown]'`
`EXPECTED_RUBY_PATCHLEVEL = '[unknown]'`
`UNKNOWN = true`
even after running `ruby extconf.rb`.

Looked to me like it was not getting overwritten, so I used `ruby -v` to get the version number and edited the file myself:
`EXPECTED_RUBY_VERSION = "2.7.0"`
`EXPECTED_RUBY_PATCHLEVEL = 0`
`UNKNOWN = false`
After this, I ran `make` and and, in vim, `:PluginUpdate`. This fixed the issue, and I was able to use command-t.
Note, I reran `ruby extconf.rb` after manually editing the file and the variables were not changed back to unkown, which is why I think the file may just not be getting written.

I am creating the issue in case others run into a similar ruby version problem. Not sure if this is something with the command-t code or just something weird in my system/setup.

My system setup:
OS: Ubuntu 20.04 LTS
vim: Vi IMproved 8.2, included patches: 1-1216
ruby: 2.7.0p0

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
