### ISSUE TITLE
Unable to hide statusline in command-t buffer

### ISSUE THREAD

**Issue by shivanshukmr** [wincent/command-t#371]
I wish to hide my statusline while in command-t buffer. I have tried using autocmds, but it doesn't seem to work. I have this in my vimrc(init.vim).

`autocmd! FileType command-t set laststatus=0
`
`
   \| autocmd BufLeave <buffer> set laststatus=2
`

I am using NVIM v0.5.0-812-gd17e50879.
Also note that this does work with other file types, only doesn't work with command-t buffer.

**Comment by shivanshukmr** [comment]
Okay, I found another method to accomplish this behaviour. For anyone else wanting the same, here is the solution.
```
autocmd! User CommandTWillShowMatchListing
autocmd User CommandTWillShowMatchListing set laststatus=0
autocmd! User CommandTDidHideMatchListing
autocmd User CommandTDidHideMatchListing set laststatus=2
```

**Comment by wincent** [comment]
Thanks for sharing your findings @shivanshukmr.
