### ISSUE TITLE
Cannot locate `extconf.rb` for compilation

### ISSUE THREAD

**Issue by captainviet** [wincent/command-t#373]
Output of executing the compilation steps:
```
cd ~/.vim/bundle/command-t/ruby/command-t/
ruby extconf.rb
```
```
[vince.dang LV:1 command-t] (master)
>> ruby extconf.rb
Traceback (most recent call last):
ruby: No such file or directory -- extconf.rb (LoadError)
```
from this path https://github.com/wincent/command-t/tree/master/ruby/command-t seems there's no such file `extconf.rb` also

**Comment by ruslanzelinskyy** [comment]
It's here
`cd ~/.vim/bundle/command-t/ruby/command-t/ext/command-t`

**Comment by captainviet** [comment]
oh thanks, I can install already!
