### ISSUE TITLE
Allow remove_buffer to delete a buffer without closing the command-t window

### ISSUE THREAD

**Issue by Aster89** [wincent/command-t#374]
I've just discovered that <kdb>Ctrl-d</kbd> deletes the selected buffer. That's great!

However, it would be even greater if the list of matched files didn't close. This way, we could keep writing/rewriting to get other matches and keep deleting buffers as we like. This can come very useful when, after a day of work, one wants to clean the buffer list before saving a session.

I would do the change myself, but that'll take the time I need to learn a bit of ruby.

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
