### ISSUE TITLE
Ctrl+F sometimes causes vim to hang

### ISSUE THREAD

**Issue by aptiko** [wincent/command-t#384]
Hi,

when the files have changed, I do this:

1. `\t` to start Command-T
2. Type in some characters and realize that it can't find the file, because it has just been added
3. Type Ctrl+F to reload the list of files

Then sometimes, but not always, it hangs and I have to kill vim. I don't know exactly when the problem happens (but it happens quite often). What should I do to debug it?

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
