### ISSUE TITLE
Error: uninitialized constant CommandT

### ISSUE THREAD

**Issue by UnkindPartition** [wincent/command-t#385]
After a recent system update, command-t is no longer usable with neovim; I get the following message:

```
Error detected while processing /home/roman/.local/share/nvim/site/pack/plugins/start/command-t/autoload/commandt.vim:
line  230:
NameError: uninitialized constant CommandT
Error detected while processing function commandt#FileFinder:
line    2:
NoMethodError: undefined method `show_file_finder' for nil:NilClass
Press ENTER or type command to continue
```

My command-t version is up to date (6a00a2cabfb5ee3f49ff556ceea56892825c03970) and the C extension is recompiled.

System info:

Arch Linux
NVIM v0.6.0

    ## Ruby provider (optional)
      - INFO: Ruby: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
      - INFO: Host: /home/roman/bin/neovim-ruby-host
      - OK: Latest "neovim" gem is installed: 0.9.0

**Comment by mkayyash** [comment]
I concur. Same exact issue after a recent system update.

My system info:
Debian Linux
NVIM v0.6.1

**Comment by wincent** [comment]
Have you tried rebuilding Command-T? Something like:

```
cd ~/.config/nvim/pack/bundle/opt/command-t/ruby/command-t/ext/command-t
make clean
ruby extconf.rb
make
```

(exact path to the `ruby/command-t/ext/command-t` is going to be system-dependent)

**Comment by mkayyash** [comment]
Thanks Greg, yes I tried that too after I updated the plugin but I'm still having the problem.

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.

**Comment by mkayyash** [comment]
Unfortunately I couldn't' get this to work so I gave up and switched to another similar extension (fzf) last week. I hope the new version of command-t addresses this issue though.

**Comment by brt** [comment]
@mkayyash I stumbled upon the exact same issue and [this comment](https://github.com/wincent/command-t/issues/388#issuecomment-1113926423) provides a very simple working solution, which is very fortunate since I find it very hard to live without this lovely plugin! (in a nutshell: for reasons beyond my humble comprehension, your Vim plugin manger needs to delay loading of this plugin to the VimEnter event)
