### ISSUE TITLE
Strange interaction with vim-gitgutter

### ISSUE THREAD

**Issue by Aster89** [wincent/command-t#386]
Hi there. I've posted [this issue](https://github.com/airblade/vim-gitgutter/issues/813) on `vim-gitgutter`. It is about a bug that is triggered by the presense of `vim-gitgutter` _and_ `command-t` together.

Would you mind giving a look there?

The point is that I don't know which of the two plugins the strange behavior is due to. I guessed it was `vim-gitgutter`, so I opened the issue there, but now I'm really puzzled. Maybe you can have a guess based on that description+demo and claim it is or can't be due to your plugin.

**Comment by Aster89** [comment]
It's actually a bug in Vim.

**Comment by wincent** [comment]
My favorite kind of bug — the one I don't have to fix! 😁
