### ISSUE TITLE
[Question] why does RubyGems version of this package contains '../..' in the gem data path?

### ISSUE THREAD

**Issue by mensfeld** [wincent/command-t#387]
Isn't that a mistake?

Please see the picture below:
![Zrzut ekranu z 2022-01-27 12-46-42](https://user-images.githubusercontent.com/392754/151352890-044857ca-50d5-4062-accf-338faf91d8e4.png)

when unpacking this lib I get `tar: Error is not recoverable: exiting now` due to:

```
tar: Removing leading `../../' from member names
tar: ../../Gemfile: Member name contains '..'
tar: ../../LICENSE: Member name contains '..'
tar: ../../README.md: Member name contains '..'
tar: ../../Rakefile: Member name contains '..'
tar: ../../doc/.gitignore: Member name contains '..'
tar: ../../doc/command-t.txt: Member name contains '..'
```

**Comment by wincent** [comment]
It's quite possible that it's been broken like that for a _long_ time[^hypothesis] — almost nobody uses the _gem_ itself, instead just installing Command-T as a Vim plug-in (by pointing a plug-in manager at the repository).

[^hypothesis]: I'm suspicious of commit 8ec8f73b4cb071e63d5a0a6ef58258c9e03fbe93 ("Move Command-T files deeper", May 23, 2016) at which point the `command-t.gemspec` file moved down two layers below the `Gemfile`.

**Comment by mensfeld** [comment]
ah, do you want me to fix this for you?

**Comment by wincent** [comment]
Sure, if you have a clear idea for _what_ to do[^i] — it may be just moving some stuff around, but we have to be careful not to break things for the 99% use case (ie. plug-in installs).

[^i]: I don't. 😬

**Comment by mensfeld** [comment]
Ok, let me close it in that case then. Not worth taking the risk.
