### ISSUE TITLE
Can only type one letter in Popup window

### ISSUE THREAD

**Issue by marcato15** [wincent/command-t#407]
I just updated to the new version but now when the UI pops, after I type the second letter the UI disappears and the letters I type start modifying whatever is in the current buffer in insert mode. Anyone else ran into that issue?

**Comment by wincent** [comment]
Hi @marcato15 — if you can provide some info about your local set-up, I might be able to repro what you're seeing, but I haven't heard any reports of this kind of thing until now: 

- **What version of Neovim are you running?** ie. `nvim --version`
- **What operating system are you running on?** (eg. macOS Monterey, Arch Linux etc)
- **What system architecture?** (eg. `arm64`, `x86_64` etc)
- **How did you install Command-T?** (eg. what package manager, if any, did you use?)
- **How have you configured Neovim and/or Command-T?**
- **Do you have a minimal repro example, or a link to your dotfiles repo?**

**Comment by marcato15** [comment]
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info
```

macOS Monterey

I'm on an M1 mac

I install Command-t using Vim-Plug

For the install and configuration

```
Plug 'wincent/command-t', {
\   'do': 'cd lua/wincent/commandt/lib && make'
\ }
....
let g:CommandTPreferredImplementation='lua'

autocmd VimEnter * call s:setup_commandt()
function! s:setup_commandt() abort
lua<<EOF
require('wincent.commandt').setup()

EOF
endfunction

nnoremap <leader>t :CommandTGit<CR>
```

**Comment by wincent** [comment]
Nothing suspicious there. What other plugins do you have installed? What settings?

**Comment by marcato15** [comment]
Here's my init.vim https://github.com/marcato15/dotfiles/blob/master/basics/.config/nvim/init.vim

**Comment by marcato15** [comment]
Here is a video of the issue
https://user-images.githubusercontent.com/413567/190019096-6a6075d9-5616-45cb-aab6-c2bce5465eee.mov

**Comment by marcato15** [comment]
I figured it out. It was my autocomplete plugin that was interfering with it. Thanks for your help. Love the update.
