### ISSUE TITLE
Missing documentation about the initial usage

### ISSUE THREAD

**Issue by flosse** [wincent/command-t#410]
I just installed this plugin but then I was lost, because I couldn't find a documentation that told me how to use it.
A quick search took me to https://www.vim.org/scripts/script.php?script_id=3025 but there was nothing helpful.
So I followed this:

> For more details see the project Git repository:
>  https://github.com/wincent/command-t

There is a lot of text in the README.md  telling me how awesome it is, but no word about how to use it.

So I followed this:
> For more information, see [the documentation](https://github.com/wincent/command-t/blob/main/doc/command-t.txt).

Finally, there was a `USAGE` section, but it only said this:

> See also |command-t-ruby-usage| for older usage information.

Honestly, is this a joke?
I mean, what's the problem with adding **one** line in the README like

> **Usage:** `<leader>t` (where the `<leader>` key usually is `\`).

**Comment by wincent** [comment]
> Honestly, is this a joke?

No, it's a [known issue](https://github.com/wincent/command-t/blob/f6a6cf7fb17cee08ca0ca84ffce6aabccc3d8476/doc/command-t.txt#L241):

```markdown
- The documentation for 6.x (ie. this document) is still a work in progress.
```

And definitely not a joke, but rather a project which I have worked on and given away under an open source license for free, for over 12 years now, and which many people have found useful.

You're welcome to send a PR improving the documentation if you'd like, but I'll get around to it sooner or later, either way, so I'll close this for now.

**Comment by wincent** [comment]
Oh, I should add — [the older docs are still in the repo](https://github.com/wincent/command-t/blob/f6a6cf7fb17cee08ca0ca84ffce6aabccc3d8476/doc/command-t-ruby.txt#L462) and may prove somewhat useful in the interim.

```
USAGE                                           *command-t-ruby-usage*

Bring up the Command-T file window by typing:

  <Leader>t

This mapping is set up automatically for you, provided you do not already have
a mapping for <Leader>t or |:CommandT|. You can also bring up the file window
by issuing the command:

  :CommandT

A prompt will appear at the bottom of the screen along with a file window
showing all of the files in the current project (the project directory is
determined according to the value of the |g:CommandTTraverseSCM| setting,
which defaults to the SCM root of the current file).

You can pass in an optional path argument to |:CommandT| (relative to the
current working directory (|:pwd|) or absolute):

  :CommandT ../path/to/other/files

Type letters in the prompt to narrow down the selection, showing only the
files whose paths contain those letters in the specified order. Letters do not
need to appear consecutively in a path in order for it to be classified as a
match.

Once the desired file has been selected it can be opened by pressing <CR>.
(By default files are opened in the current window, but there are other
mappings that you can use to open in a vertical or horizontal split, or in
a new tab.) Note that if you have |'nohidden'| set and there are unsaved
changes in the current window when you press <CR> then opening in the current
window would fail; in this case Command-T will open the file in a new split.
```

(Continues...)
