### ISSUE TITLE
Backspace key closes Command-T and enters insert mode

### ISSUE THREAD

**Issue by mikkelsvartveit** [wincent/command-t#411]
Hi! I'm having an issue where Command-T closes when I press the backspace key. It also enters insert mode in the open window. Any idea why this happens? I'm using the new Lua implementation.

**Comment by wincent** [comment]
@mikkelsvartveit Yours is the first report I've heard of something like this. Can you provide a bit more info that might help to reproduce the issue?

- **What version of Neovim are you running?** ie. `nvim --version`
- **What operating system are you running on?** (eg. macOS Monterey, Arch Linux etc)
- **What system architecture?** (eg. `arm64`, `x86_64` etc)
- **How did you install Command-T?** (eg. what package manager, if any, did you use?)
- **How have you configured Neovim and/or Command-T?**
- **Do you have a minimal repro example, or a link to your dotfiles repo?**
- **What other plug-ins do you have running, and have you tried reproducing the problem without them?**

**Comment by jannishuebl** [comment]
Hi, 

I am having the same Problem. @mikkelsvartveit have you figured out what caused this behaviour?

**Comment by wincent** [comment]
> I am having the same Problem. [@mikkelsvartveit](https://github.com/mikkelsvartveit) have you figured out what caused this behaviour?

@jannishuebl I'd ask you the same questions [I posted above](https://github.com/wincent/command-t/issues/411#issuecomment-1257883935):

> Can you provide a bit more info that might help to reproduce the issue?
> 
> * **What version of Neovim are you running?** ie. `nvim --version`
> * **What operating system are you running on?** (eg. macOS Monterey, Arch Linux etc)
> * **What system architecture?** (eg. `arm64`, `x86_64` etc)
> * **How did you install Command-T?** (eg. what package manager, if any, did you use?)
> * **How have you configured Neovim and/or Command-T?**
> * **Do you have a minimal repro example, or a link to your dotfiles repo?**
> * **What other plug-ins do you have running, and have you tried reproducing the problem without them?**

**Comment by jannishuebl** [comment]
What version of Neovim are you running? ie. nvim --version

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"


What operating system are you running on? (eg. macOS Monterey, Arch Linux etc)

6.6.4-arch1-1

What system architecture? (eg. arm64, x86_64 etc)
amd64

How did you install Command-T? (eg. what package manager, if any, did you use?)

Plug packagemanager

How have you configured Neovim and/or Command-T?

No special config

Do you have a minimal repro example, or a link to your dotfiles repo?



What other plug-ins do you have running, and have you tried reproducing the problem without them?

I have only tried to delete few, but not step by step:

Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'MunifTanjim/nui.nvim'

Plug 'neovim/nvim-lspconfig'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-buffer'
Plug 'nvim-lua/plenary.nvim'
Plug 'petertriho/cmp-git'
Plug 'hrsh7th/cmp-path'
Plug 'hrsh7th/cmp-cmdline'
Plug 'hrsh7th/nvim-cmp'

Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.5' }

      
Plug 'leafOfTree/vim-vue-plugin'
Plug 'leafgarland/typescript-vim'
" html formating
Plug 'maksimr/vim-jsbeautify'
Plug 'benekastah/neomake'
" file tree
Plug 'scrooloose/nerdtree'
" file tree and tabs interaction
Plug 'jistr/vim-nerdtree-tabs'
" commenting
Plug 'scrooloose/nerdcommenter'
Plug 'vim-scripts/taglist.vim'
Plug 'szw/vim-tags'
Plug 'tpope/vim-fugitive'
Plug 'scrooloose/syntastic'
Plug 'msanders/snipmate.vim'
Plug 'tpope/vim-surround'
Plug 'tsaleh/vim-align'
Plug 'rking/ag.vim'
Plug 'austintaylor/vim-indentobject'
Plug 'bling/vim-airline'
Plug 'sjl/splice.vim'
Plug 'tpope/vim-endwise'
Plug 'Raimondi/delimitMate'
Plug 'hsitz/VimOrganizer'
Plug 'sjl/gundo.vim'
Plug 'AndrewRadev/switch.vim'
Plug 'tpope/vim-dispatch'
Plug 'airblade/vim-gitgutter'
Plug 'mattn/emmet-vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'mattn/webapi-vim'
Plug 'mattn/vdbi-vim'

Plug 'nvim-lua/plenary.nvim'
Plug 'petertriho/cmp-git'

" Ruby/Rails

Plug 'tpope/vim-rails'
Plug 'tpope/vim-bundler'
Plug 'tpope/vim-rake'
Plug 'nelstrom/vim-textobj-rubyblock'
Plug 'ecomba/vim-ruby-refactoring'
Plug 'vim-scripts/blockle.vim'
Plug 'jannishuebl/vim-rspec'

Plug 'vim-airline/vim-airline-themes'
Plug 'altercation/vim-colors-solarized'
Plug 'tpope/vim-vividchalk'
Plug 'chriskempson/tomorrow-theme', {'rtp': 'vim/'}

Plug 'vim-ruby/vim-ruby'
Plug 'tsaleh/vim-tmux'
Plug 'elzr/vim-json'
Plug 'tpope/vim-cucumber'
Plug 'tpope/vim-haml'
Plug 'tpope/vim-markdown'
Plug 'kchmck/vim-coffee-script'
Plug 'vitaly/vim-syntastic-coffee'
Plug 'vim-scripts/jade.vim'
Plug 'wavded/vim-stylus'
Plug 'slim-template/vim-slim'
Plug 'elixir-lang/vim-elixir'
Plug 'Blackrush/vim-gocode'
Plug 'ekalinin/Dockerfile.vim'
Plug 'groenewege/vim-less'
Plug 'mustache/vim-mustache-handlebars'
Plug 'mtscout6/vim-cjsx'
Plug 'vitaly/vim-literate-coffeescript'
Plug 'rust-lang/rust', {'rtp': 'src/etc/vim/'}
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'jeetsukumaran/vim-buffergator'

Plug 'mzlogin/vim-markdown-toc'

Plug 'guns/vim-clojure-static'
Plug 'tpope/vim-fireplace'
Plug 'kien/rainbow_parentheses.vim'

Plug 'kana/vim-textobj-user'
Plug 'tpope/vim-repeat'
Plug 'vitaly/vim-gitignore'

Plug 'wincent/command-t'
Plug 'Shougo/unite.vim'
Plug 'Shougo/unite-outline'
Plug 'ujihisa/unite-colorscheme'
Plug 'jalvesaq/Nvim-R'

**Comment by fogine** [comment]
fyi ` Raimondi/delimitMate` plugin is causing the issue.

You can fix it by disabling the plugin for command-t

> au FileType command-t,CommandTPrompt let b:loaded_delimitMate = 1
