### ISSUE TITLE
Installation Instructions Unclear

### ISSUE THREAD

**Issue by amab8901** [wincent/command-t#412]
Please make the installation instructions (https://github.com/wincent/command-t/blob/main/doc/command-t.txt) more clear.

Instruction:
`cd` into the `lua/wincent/commandt/lib/` directory

Comment:
What if I don't have such a directory? And where does the lua directory begin? In root folder? In home directory? Please specify.

Instruction:
type:
>
    make
<

Comment:
I type it, and it says:
```make: *** No targets specified and no makefile found.  Stop.```
Something isn't right here. Which target should I specify? And how should I deal with the makefile?

Instruction:
See also |command-t-ruby-installation| for older installation instructions

Comment: 
That section apparently doesn't exist. Or at least I couldn't find it. Any links perhaps?

**Comment by wincent** [comment]
Hi @amab8901. Yeah, it's a bit tricky, and the docs are a bit of a work-in-progress.

> What if I don't have such a directory?

If you have Command-T, you have the directory, but I can't know _where_ you have it so I can't really put that in the docs... like, did you clone the Git repo? Did you use a plug-in manager? If so, which one? How is it configured?

[A few lines up from there](https://github.com/wincent/command-t/blob/f6a6cf7fb17cee08ca0ca84ffce6aabccc3d8476/doc/command-t.txt#L52), it says:

> Run `:checkhealth wincent.commandt` to confirm that the C library has been built, and check for the presence of the optional executable helpers.

If you put Command-T in "the right place" (usually the case if you used a plug-in manager to do so), then that will print out the exact path. For example, this is what it prints on my system:

```
wincent.commandt: require("wincent.commandt.health").check()
========================================================================
  - INFO: Command-T version: 6.0.0-a.4

## Checking that C library has been built
  - INFO: Build directory is:
    /Users/wincent/.config/nvim/pack/bundle/opt/command-t/lua/wincent/commandt/lib
  - OK: library can be `require`-ed and functions called

## Checking for optional external dependencies
  - OK: (optional) `git` binary found
  - OK: (optional) `rg` binary found
  - OK: (optional) `find` binary found
  - OK: (optional) `watchman` binary found
```

So, for me that means I have to `cd /Users/wincent/.config/nvim/pack/bundle/opt/command-t/lua/wincent/commandt/lib` before running `make`.

I probably need to add a section listing a few common plug-in managers and installation locations, and put the prompt to run `:checkhealth` front and center in the docs.

> That section apparently doesn't exist. Or at least I couldn't find it.

It's [here](https://github.com/wincent/command-t/blob/f6a6cf7fb17cee08ca0ca84ffce6aabccc3d8476/doc/command-t-ruby.txt#L144). But if you're using the Lua implementation, you probably won't have much need for the Ruby implementation. You can still run the build commands mentioned there though if you want.

**Comment by wincent** [comment]
I've not used vim-plug myself but this bit looks about right:

```
Plug 'wincent/command-t'
```

(Not sure you need to pass a path to `call plug#begin()` though — the docs say that a presumably reasonable default will be used if you don't.)

Did you actually run `:PlugInstall` to install the plugin though? After that, I would expect `:checkhealth wincent.commandt` to work.

**Comment by amab8901** [comment]
Oh, the problem was caused by my move from Vim to Neovim. Neovim doesn't use `~/.vimrc` for its configuration (unlike Vim), but rather Neovim configurations are put in here: `~/.config/nvim/init.vim`. After I made that discovery, I could easily figure out how to get CommandT to work. At least in the sense that `:checkhealth wincent.commandt` in nvim produces the following output:

```
wincent.commandt: require("wincent.commandt.health").check()
========================================================================
  - INFO: Command-T version: 6.0.0-a.4

## Checking that C library has been built
  - INFO: Build directory is:
    /home/amab/.vim/plugged/command-t/lua/wincent/commandt/lib
  - OK: library can be `require`-ed and functions called

## Checking for optional external dependencies
  - OK: (optional) `find` binary found
  - OK: (optional) `rg` binary found
  - OK: (optional) `git` binary found
  - WARNING: (optional) `watchman` binary is not in $PATH
    - ADVICE:
      - commandt.watchman_finder requires `watchman`
```
