### ISSUE TITLE
Trouble getting command-t to work

### ISSUE THREAD

**Issue by helgar** [wincent/command-t#419]
Hi,

big fan of command-t. Thanks for creating and maintaining it!

I recently tried to switch to the new version, but I cannot get it to work.

I use vim version 9.0.1189 on Ubuntu 22.04.

I cloned the git repo into .vim/pack/vendor/start/command-t and ran `make` and everything seems to be fine.

However, when I try to use it, the <leader>t command does not show anything, just emits a beep. No error or any message whatsoevar, hence hard to debug.

This is the command-t related content of my .vimrc:

```
let g:CommandTTraverseSCM = "pwd"
let g:CommandTMaxFiles=50000
```

After trying to debug this for a while, I fell back on the ruby version by adding 
```
let g:CommandTPreferredImplementation='ruby'
```

However, I would love to use the new version, but am lost as to what is wrong with my setup.

Thank you!

**Comment by wincent** [comment]
The Lua version won't work on Vim, only on Neovim. It relies on a bunch of Lua APIs provided only by Neovim.

As you've discovered, the Ruby code is still all there though and can be used as a fallback on Vim.

(Speculative: maybe Vim and Neovim will converge again in the future, at least as far as the Lua APIs go — and perhaps further — but we'll see.)

**Comment by wincent** [comment]
FWIW, I'll try to make the failure a bit less mysterious when trying to run with Vim.

**Comment by helgar** [comment]
Hi, 

thanks for the clarification.

Indeed, I guess it would help, if this was a bit more discoverable - either when running make or in the documentation.

I'll stick to the old version for now then. Hope you still keep that alive :)

Thank you,
Helga

**Comment by wincent** [comment]
> I'll stick to the old version for now then. Hope you still keep that alive :)

Yep, I have no plans to get rid of it 😁 — as I wrote [here](https://wincent.com/blog/command-t-lua-rewrite), I expect to keep it around indefinitely.
