### ISSUE TITLE
Custom prioritisation of file extensions

### ISSUE THREAD

**Issue by hugovincent** [wincent/command-t#79]
Is it possible to configure Command-T to prioritise certain file extensions/suffixes over others? (Command-T seems to ignore the vim suffixes variable as far as I can tell, as well as the project .gitignore file.). My use case is editing source-to-source languages like Coffee-script and Stylus: Command-T favours the output/generated files (*.css, *.js, etc) over the source files (*.styl, *.coffee, etc). Thanks!

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
