### ISSUE TITLE
Command-T failed to load: `LoadError: cannot load such file -- command-t/stub` (works normally)

### ISSUE THREAD

**Issue by blueyed** [wincent/command-t#92]
For some reason, I've received the following error when calling `:CommandT`:

```
Error detected while processing …/vim/neobundles/command-t/autoload/commandt.vim:
line  193:
LoadError: cannot load such file -- command-t/stub
Error detected while processing function commandt#CommandTShowFileFinder:
line    2:
NoMethodError: undefined method `show_file_finder' for nil:NilClass
Error detected while processing function commandt#CommandTShowFileFinder:
line    2:
NoMethodError: undefined method `show_file_finder' for nil:NilClass
```

Command-T usually works. This just happened, but it works in a new Vim instance.

In the broken Vim instance, `:ruby puts $:` gives:

```
usr/local/lib/site_ruby/1.9.1
/usr/local/lib/site_ruby/1.9.1/x86_64-linux
/usr/local/lib/site_ruby
/usr/lib/ruby/vendor_ruby/1.9.1
/usr/lib/ruby/vendor_ruby/1.9.1/x86_64-linux
/usr/lib/ruby/vendor_ruby
/usr/lib/ruby/1.9.1
/usr/lib/ruby/1.9.1/x86_64-linux
```

The related code in Command-T:
https://github.com/wincent/command-t/blob/master/autoload/commandt.vim#L190

After this, each entering of a buffer causes this error:

```
Error detected while processing BufEnter Auto commands for "*":
NameError: uninitialized constant CommandT
```

(see also #91 about an option to delete these autocommands).

After a successful invocation of `:CommandT`, the bundles path is added to `$:`:

```
/home/user/.vim/neobundles/command-t//ruby
```

**Comment by exussum12** [comment]
This has just happend to me 

/home/scott/.vim
/home/scott/.vim/bundle/command-t
/var/lib/vim/addons
/usr/share/vim/vimfiles
/usr/share/vim/vim80
/usr/share/vim/vimfiles/after
/var/lib/vim/addons/after
/home/scott/.vim/after


Happens consistently. Fresh install via pathogen 

Any ideas?

**Comment by exussum12** [comment]
Ignore that, I had a stray file from another command t version.removing that stopped it

**Comment by wincent** [comment]
Ok!
