### ISSUE TITLE
Allow to cancel scanning

### ISSUE THREAD

**Issue by blueyed** [wincent/command-t#93]
It would be helpful, if you could abort the scanner (using Ctrl-C).

It appears the (GNU) find-based scanner behaves better than the (default) ruby one.
Is this the case?

Is this a limitation from Vim?
Would it help to make use of [vimproc](https://github.com/Shougo/vimproc.vim) if it is available?

The usual case where I need to do this when I've accidentally invoked Command-T on a wrong (and huge) directory.

I've noticed in this regard, that there might be Vim errors afterwards (like `missing :endif` - just from the top of my head, not sure about this), but these are normally fixed when invoking `:CommandT` again.

I have recently switched back from the (GNU) find-based scanner to the ruby scanner, because the find-based scanner does not exclude/handle g:CommandTWildIgnore during scanning (and I use it to exclude (very) slow directories, like sshfs mounts).

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
