### ISSUE TITLE
Command-T segfaults.

### ISSUE THREAD

**Issue by amalantony** [wincent/command-t#97]
On invoking command-T in vim, a segfault is thrown and vim exits. The latest Command-T commit  is 2b69d1b2635814a786e2c207fea2e5. 

The error thrown is:

```
Vim: Caught deadly signal SEGV
Vim: Finished.
Vim: Finished.
Vim: Caught deadly signal SEGV
Vim: Finished.
```

  Segmentation fault (core dumped)

Any thoughts?

**Comment by peregrinogris** [comment]
Not strictly related to this bug, but I experienced the same segfault on my install, and this was the closest issue I could find.

Yesterday I upgraded to OSX Yosemite from Mavericks, and so Command-T ceased to function. I tried to recompile, but ruby was complaining of not finding some header files, and the solution to that was to update the command line tools that I had forgotten to update. After that, I could run make again.

But even after re-running make, it seems it didn't make a clobber build but just recompiled a single file, and Command-T still segfaulted when trying to open it. I was kind of out of solutions so I tried the nuke approach removing the `~/.vim/bundle/command-t` directory and cloning it again + rebuild, and it worked. This time make compiled all the files and Command-T didn't crash.

For some context, I was using Command-T 1.11 and Mavericks, and then upgraded to 1.12 and Yosemite.

**Comment by wincent** [comment]
@peregrinogris: did you `make clean` at any point along the way?

I would expect that it wouldn't rebuild if the underlying timestamps of the source files and the built extension haven't changed (which they won't when you do a system upgrade). Unfortunately, updating the timestamp on the `Makefile` itself won't help either (eg. if you do `ruby extconf.rb`), and the only way to force a rebuild is to `make clean` first, or like you tried, blow away the entire `~/.vim/bundle/command-t/ruby/command-t` directory.

**Comment by peregrinogris** [comment]
@wincent sorry, dind't try a `make clean`, that would probably have worked.

**Comment by scott-silver** [comment]
Same problem here. Got `Vim: Caught deadly signal SEGV` issue after updating to OSX El Capitan (10.11.4). `make clean` didn't work, and the version of Ruby I was using (with rvm) matched exactly the results of `:ruby puts "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"`.

Finally fixed the problem by running `ruby extconf.rb` using the version of Ruby which comes packaged with El Capitan, similar to what @notduncansmith recommended here (https://github.com/Homebrew/legacy-homebrew/issues/23938#issuecomment-43967839):

```
cd ~/.vim/bundle/command-t/ruby/command-t
rm Makefile
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
make
sudo make install
```

**Comment by MACSkeptic** [comment]
@scott-silver thank you so much, that fixed it for me (using the ruby version from OSX)

**Comment by hjma29** [comment]
@scott-silver solution works for me also on MacOS Sierra. (without it, just make clean and ruby extconf.rb|make didn't work)

have 2.0.0p648 for both vim/mvim and system but got SEGV crash when launching command-T.

//this is what installed from rvm
→ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-darwin16.1.0]

//this is from MAC.
→ /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

my execonf.rb directory is at
~/.vim/plugged/command-t/ruby/command-t/ext/command-t
